Add support for Magpie Newtork FS

diff --git a/hadoop-run b/hadoop-run
--- a/hadoop-run
+++ b/hadoop-run
@@ -43,9 +43,10 @@ fi
 if [ "${HADOOP_FILESYSTEM_MODE}" != "hdfs" ] \
     && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsoverlustre" ] \
     && [ "${HADOOP_FILESYSTEM_MODE}" != "rawnetworkfs" ] \
-    && [ "${HADOOP_FILESYSTEM_MODE}" != "intellustre" ]
+    && [ "${HADOOP_FILESYSTEM_MODE}" != "intellustre" ] \
+    && [ "${HADOOP_FILESYSTEM_MODE}" != "magpienetworkfs" ]
 then
-    echo "HADOOP_FILESYSTEM_MODE must be set to hdfs, hdfsoverlustre, rawnetworkfs, or intellustre"
+    echo "HADOOP_FILESYSTEM_MODE must be set to hdfs, hdfsoverlustre, rawnetworkfs, intellustre, or magpienetworkfs"
     exit 1
 fi
 
@@ -171,6 +172,21 @@ if [ "${HADOOP_FILESYSTEM_MODE}" == "intellustre" ] \
 then
     echo "Must specify environment variable HADOOP_INTELLUSTRE_PATH"
     exit 1
+fi
+
+if [ "${HADOOP_FILESYSTEM_MODE}" == "magpienetworkfs" ] \
+    && [ "${HADOOP_MAGPIENETWORKFS_PATH}X" == "X" ]
+then
+    echo "Must specify environment variable HADOOP_MAGPIENETWORKFS_PATH"
+    exit 1
+
+    firstchar="$(echo ${HADOOP_MAGPIENETWORKFS_PATH} | head -c 1)"
+
+    if [ "${firstchar}" != "/" ]
+    then
+	echo "HADOOP_MAGPIENETWORKFS_PATH must be an absolute path"
+	exit 1
+    fi
 fi
 
 if [ "${HADOOP_INTELLUSTRE_SHUFFLE}X" != "X" ] \
@@ -324,7 +340,8 @@ then
     # Default block size is 1M in Lustre
     # XXX: If not default, can get from lctl or similar?
     iobuffersize=1048576
-elif [ "${HADOOP_FILESYSTEM_MODE}" == "rawnetworkfs" ]
+elif [ "${HADOOP_FILESYSTEM_MODE}" == "rawnetworkfs" ] \
+    || [ "${HADOOP_FILESYSTEM_MODE}" == "magpienetworkfs" ]
 then
     # Assuming Lustre, so copy above 1M
     iobuffersize=1048576
@@ -526,6 +543,15 @@ then
 else
     mapoutputcollectorclass="org.apache.hadoop.mapred.MapTask\$MapOutputBuffer"
     reduceshuffleconsumerplugin="org.apache.hadoop.mapreduce.task.reduce.Shuffle"
+fi
+
+if [ "${HADOOP_MAGPIENETWORKFS_BLOCKSIZE}X" != "X" ] \
+    && [ "${HADOOP_FILESYSTEM_MODE}" == "magpienetworkfs" ]
+then
+    magpienetworkfsblocksize=${HADOOP_MAGPIENETWORKFS_BLOCKSIZE}
+else
+    # 32M is Hadoop default for local
+    magpienetworkfsblocksize=33554432
 fi
 
 if [ "${HADOOP_DAEMON_HEAP_MAX}X" != "X" ]
@@ -733,6 +759,36 @@ then
     format=0
 
     pathcount=1
+elif [ "${HADOOP_FILESYSTEM_MODE}" == "magpienetworkfs" ]
+then
+    # Setup node directory per node, still need for "local" files
+    fspath="${HADOOP_MAGPIENETWORKFS_PATH}"
+    pernodepath="${fspath}/node-${HADOOP_CLUSTER_NODERANK}"
+    hadooptmpdir=`echo "${pernodepath}" | sed "s/\\//\\\\\\\\\//g"`
+    fsdefault=`echo "magpienetworkfs:///" | sed "s/\\//\\\\\\\\\//g"`
+    magpienetworkfsbase=`echo "${fspath}" | sed "s/\\//\\\\\\\\\//g"`
+
+    if [ ! -d "${fspath}" ]
+    then
+        mkdir -p ${fspath}
+        if [ $? -ne 0 ] ; then
+            echo "mkdir failed making ${fspath}"
+            exit 1
+        fi
+    fi
+
+    if [ ! -d "${pernodepath}" ]
+    then
+        mkdir -p ${pernodepath}
+        if [ $? -ne 0 ] ; then
+            echo "mkdir failed making ${pernodepath}"
+            exit 1
+        fi
+    fi
+
+    format=0
+
+    pathcount=1
 else
     echo "Illegal HADOOP_FILESYSTEM_MODE \"${HADOOP_FILESYSTEM_MODE}\" specified"
     exit 1
@@ -741,6 +797,7 @@ fi
 if ([ "${HADOOP_FILESYSTEM_MODE}" == "hdfsoverlustre" ] \
     || [ "${HADOOP_FILESYSTEM_MODE}" == "rawnetworkfs" ] \
     || [ "${HADOOP_FILESYSTEM_MODE}" == "intellustre" ]) \
+    || [ "${HADOOP_FILESYSTEM_MODE}" == "magpienetworkfs" ] \
     && [ "${HADOOP_LOCALSTORE}X" != "X" ]
 then
     IFSORIG=${IFS}
@@ -846,6 +903,8 @@ then
 	-e "s/INTELLUSTREBLOCKSIZE/${intellustreblocksize}/g" \
 	-e "s/INTELLUSTRESTRIPESIZE/${intellustrestripesize}/g" \
 	-e "s/INTELLUSTRESTRIPECOUNT/${intellustrestripecount}/g" \
+	-e "s/MAGPIENETWORKFSBASEDIR/${magpienetworkfsbase}/g" \
+	-e "s/MAGPIENETWORKFSBLOCKSIZE/${magpienetworkfsblocksize}/g" \
 	$coresitexml > ${HADOOP_CONF_DIR}/core-site.xml
 
     sed -e "s/HADOOP_MASTER_HOST/${master}/g" \
