Add basic support for Tachyon

diff --git a/magpie-run b/magpie-run
--- a/magpie-run
+++ b/magpie-run
@@ -925,12 +925,175 @@ else
     stormsetupcomplete=1
 fi
 
+#
+# Setup Tachyon
+#
+
+if [ "${TACHYON_SETUP}" == "yes" ]
+then
+    cd ${TACHYON_HOME}
+
+    if [ ${TACHYON_MODE} != "setuponly" ]
+    then
+	# Must be done here instead of in magpie-setup-tachyon, b/c
+	# if Hadoop is setup, the format needs to contact HDFS
+	if [ "${TACHYON_JOURNAL_FOLDER}X" == "X" ]
+	then
+	    tachyonformat=1
+	else
+	    if [ ! -d "${TACHYON_JOURNAL_FOLDER}" ]
+	    then
+		tachyonformat=1
+
+		mkdir -p ${TACHYON_JOURNAL_FOLDER}
+		if [ $? -ne 0 ] ; then
+		    echo "mkdir failed making ${TACHYON_JOURNAL_FOLDER}"
+		    exit 1
+		fi
+	    else
+		tachyonformat=0
+	    fi
+	fi
+
+	if [ "${tachyonformat}" == "1" ]
+	then
+	    echo "*******************************************************"
+	    echo "* Formatting Tachyon"
+	    echo "*******************************************************"
+	    ${tachyoncmdprefix}/tachyon format
+
+            # My rough estimate for setup time is 15 seconds per 128 nodes
+	    sleepwait=`expr ${TACHYON_SLAVE_COUNT} \/ 128 \* 15`
+	    if [ ${sleepwait} -lt 15 ]
+	    then
+		sleepwait=15
+	    fi
+	    echo "Waiting ${sleepwait} seconds to allow Tachyon format to complete"
+	    sleep ${sleepwait}
+	    totalsleepwait=`expr ${totalsleepwait} + ${sleepwait}`
+	fi
+
+	echo "Starting tachyon"
+	${tachyoncmdprefix}/tachyon-start.sh -N all NoMount
+	
+        # My rough estimate for setup time is 30 seconds per 128 nodes
+	sleepwait=`expr ${TACHYON_SLAVE_COUNT} \/ 128 \* 30`
+	if [ ${sleepwait} -lt 30 ]
+	then
+            sleepwait=30
+	fi
+	echo "Waiting ${sleepwait} seconds to allow Tachyon daemons to setup"
+	sleep ${sleepwait}
+	totalsleepwait=`expr ${totalsleepwait} + ${sleepwait}`
+    fi
+
+    echo "*******************************************************"
+    echo "*"
+    echo "* Tachyon Information"
+    echo "*"
+    echo "* You can view your Tachyon status by launching a web browser and pointing to ..."
+    echo "*"
+    echo "* Tachyon UI: http://${TACHYON_MASTER_NODE}:${TACHYON_MASTER_WEB_PORT}"
+    echo "*" 
+    echo "* To access Tachyon directly, you'll most likely want to:"
+    echo "*   ${magpieremotecmd} <WORKERNODE>"
+    if echo $SHELL | grep -q csh
+    then
+	echo "*   setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\""
+    else
+	echo "*   export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\""
+    fi
+    echo "*   cd $TACHYON_HOME"
+    echo "*"
+    echo "* Then you can do as you please.  For example:"
+    echo "*" 
+    echo "*   ${tachyoncmdprefix}/tachyon tfs ls /"
+    echo "*" 
+
+    if [ "${TACHYON_MODE}" == "setuponly" ]
+    then
+ 	echo "* To setup, you probably want to run:" 
+	echo "*"
+	echo "*   ${magpieremotecmd} ${TACHYON_MASTER_NODE}"
+	if echo $SHELL | grep -q csh
+	then
+	    echo "*   setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\""
+	else
+	    echo "*   export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\""
+	fi
+	echo "*   cd $TACHYON_HOME"
+	echo "*   ${tachyoncmdprefix}/tachyon format"
+	echo "*   ${tachyoncmdprefix}/tachyon-start.sh -N all NoMount"
+	echo "*" 
+    fi
+
+    echo "* To end/cleanup your session, kill the daemons via:"
+    echo "*" 
+    echo "*   ${magpieremotecmd} ${TACHYON_MASTER_NODE}"
+    if echo $SHELL | grep -q csh
+    then
+	echo "*   setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\""
+    else
+	echo "*   export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\""
+    fi
+    echo "*   cd $TACHYON_HOME"
+    echo "*   ${tachyoncmdprefix}/tachyon-stop.sh all"
+    echo "*" 
+    echo "* Some additional environment variables you may sometimes wish to set"
+    echo "*" 
+    if echo $SHELL | grep -q csh
+    then
+	echo "*   setenv JAVA_HOME \"${JAVA_HOME}\""
+	echo "*   setenv TACHYON_HOME \"${TACHYON_HOME}\""
+    else
+	echo "*   export JAVA_HOME=\"${JAVA_HOME}\""
+	echo "*   export TACHYON_HOME=\"${TACHYON_HOME}\""
+    fi
+
+    if [ "${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}X" != "X" ]
+    then
+	echo "*"
+	echo "* If running interactively, sourcing"
+	echo "*"
+	echo "* ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}"
+	echo "*"
+	echo "* will set most common environment variables for your job."
+    fi
+    echo "*" 
+    echo "*******************************************************"
+
+    if [ "${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}X" != "X" ]
+    then
+	if echo $SHELL | grep -q csh
+	then
+	    echo "setenv TACHYON_HOME \"${TACHYON_HOME}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+	    echo "setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+	    echo "setenv TACHYON_LOG_DIR \"${TACHYON_LOG_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+	    echo "setenv TACHYON_MASTER_NODE \"${TACHYON_MASTER_NODE}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+	    echo "setenv TACHYON_SLAVE_COUNT \"${TACHYON_SLAVE_COUNT}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+	else
+	    echo "export TACHYON_HOME=\"${TACHYON_HOME}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+	    echo "export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+	    echo "export TACHYON_LOG_DIR=\"${TACHYON_LOG_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+	    echo "export TACHYON_MASTER_NODE=\"${TACHYON_MASTER_NODE}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+	    echo "export TACHYON_SLAVE_COUNT=\"${TACHYON_SLAVE_COUNT}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+	fi
+	echo "" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+    fi
+
+    # Nothing to check for Tachyon, setup always completes
+    tachyonsetupcomplete=1
+else
+    tachyonsetupcomplete=1
+fi
+
 # Make sure all setup passed
 if [ "${zookeepersetupcomplete}" == "1" ] \
     && [ "${hadoopsetupcomplete}" == "1" ] \
     && [ "${hbasesetupcomplete}" == "1" ] \
     && [ "${sparksetupcomplete}" == "1" ] \
-    && [ "${stormsetupcomplete}" == "1" ]
+    && [ "${stormsetupcomplete}" == "1" ] \
+    && [ "${tachyonsetupcomplete}" == "1" ]
 then
     setupcomplete=1
 else
@@ -1143,6 +1306,31 @@ then
 	    sleep ${stormsleepseconds}
 	fi
     fi
+elif [ "${MAGPIE_JOB_TYPE}" == "tachyon" ]
+then
+    if [ "${setupcomplete}" == "1" ]
+    then
+	if [ "${TACHYON_MODE}" == "testtachyon" ]
+	then
+	    echo "*******************************************************"
+	    echo "* Running Testtachyon"
+	    echo "*******************************************************"
+	    ${MAGPIE_SCRIPTS_HOME}/magpie-run-tachyon-testtachyon &
+	    scriptpid=$!
+	    Magpie_wait_script ${scriptpid}
+	elif [ "${TACHYON_MODE}" == "launch" ] \
+	    || [ "${TACHYON_MODE}" == "setuponly" ]
+	then
+	    echo "*******************************************************"
+	    echo "* Entering Tachyon ${TACHYON_MODE} mode"
+	    echo "*******************************************************"
+	    
+	    tachyonsleepamounttemp=`expr ${MAGPIE_TIMELIMIT_MINUTES} - ${MAGPIE_STARTUP_TIME}`
+	    tachyonsleepamount=`expr ${tachyonsleepamounttemp} - ${MAGPIE_SHUTDOWN_TIME}`
+	    tachyonsleepseconds=`expr ${tachyonsleepamount}  \* 60`
+	    sleep ${tachyonsleepseconds}
+	fi
+    fi
 elif [ "${MAGPIE_JOB_TYPE}" == "zookeeper" ]
 then
     if [ "${setupcomplete}" == "1" ]
@@ -1227,6 +1415,18 @@ then
 	fi
 	
 	${hbasesetupscriptprefix}/stop-hbase.sh
+    fi
+fi
+
+# Tachyon before Hadoop shutdown, may need to flush
+if [ "${TACHYON_SETUP}" == "yes" ]
+then
+    if [ ${TACHYON_MODE} != "setuponly" ]
+    then
+	cd ${TACHYON_HOME}
+
+	echo "Stopping tachyon"
+	${tachyoncmdprefix}/tachyon-stop.sh all
     fi
 fi
 
diff --git a/magpie-setup-core b/magpie-setup-core
--- a/magpie-setup-core
+++ b/magpie-setup-core
@@ -160,6 +160,31 @@ then
 fi
 
 #
+# Setup Tachyon directories
+#
+
+if [ "${TACHYON_SETUP}" == "yes" ]
+then
+    mkdir -p $TACHYON_LOCAL_JOB_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${TACHYON_LOCAL_JOB_DIR}"
+	exit 1
+    fi
+    
+    mkdir -p $TACHYON_CONF_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${TACHYON_CONF_DIR}"
+	exit 1
+    fi
+
+    mkdir -p $TACHYON_LOG_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${TACHYON_LOG_DIR}"
+	exit 1
+    fi
+fi
+
+#
 # Setup Zookeeper directories
 #
 
@@ -282,6 +307,15 @@ if [ "${STORM_SETUP}" == "yes" ]
 then
     cp ${MAGPIE_LOCAL_DIR}/job_masters ${STORM_CONF_DIR}/masters
     cp ${MAGPIE_LOCAL_DIR}/job_slaves ${STORM_CONF_DIR}/workers
+fi
+
+if [ "${TACHYON_SETUP}" == "yes" ]
+then
+    # Tachyon assumes setup node is master, so no need for masters
+    # file but we still output it b/c there are functions in Magpie
+    # that assume it exists 
+    cp ${MAGPIE_LOCAL_DIR}/job_masters ${TACHYON_CONF_DIR}/masters
+    cp ${MAGPIE_LOCAL_DIR}/job_slaves ${TACHYON_CONF_DIR}/workers
 fi
 
 exit 0
