Support thread or mapreduce for Hbase performance evaluation

diff --git a/magpie-check-inputs b/magpie-check-inputs
--- a/magpie-check-inputs
+++ b/magpie-check-inputs
@@ -741,12 +741,21 @@ then
     then
 	if [ "${HBASE_PERFORMANCEEVAL_MODE}X" != "X" ]
 	then
-	    if [ "${HBASE_PERFORMANCEEVAL_MODE}" != "sequential" ] \
-		&& [ "${HBASE_PERFORMANCEEVAL_MODE}" != "random" ]	
+	    if [ "${HBASE_PERFORMANCEEVAL_MODE}" != "sequential-thread" ] \
+		&& [ "${HBASE_PERFORMANCEEVAL_MODE}" != "sequential-mr" ] \
+		&& [ "${HBASE_PERFORMANCEEVAL_MODE}" != "random-thread" ] \
+		&& [ "${HBASE_PERFORMANCEEVAL_MODE}" != "random-mr" ]
 	    then
-		echo "HBASE_PERFORMANCEEVAL_MODE must be sequential or random"
+		echo "HBASE_PERFORMANCEEVAL_MODE must be sequential-thread, sequential-mr, random-thread, or random-mr"
 		exit 1
 	    fi
+	fi
+
+	if ([ "${HADOOP_SETUP_TYPE}" == "HDFS1" ] || [ "${HADOOP_SETUP_TYPE}" == "HDFS2" ]) \
+	    && (["${HBASE_PERFORMANCEEVAL_MODE}" == "sequential-mr" ] || [ "${HBASE_PERFORMANCEEVAL_MODE}" == "random-mr" ])
+	then
+	    echo "Cannot execute MapReduce performance evaluation if HADOOP_SETUP_TYPE set to ${HADOOP_SETUP_TYPE}"
+	    exit 1
 	fi
 
 	if [ "${HBASE_PERFORMANCEEVAL_ROW_COUNT}X" != "X" ]
