Support HADOOP_TERASORT_RUN_TERAVALIDATE option

diff --git a/magpie-run-hadoop-terasort b/magpie-run-hadoop-terasort
--- a/magpie-run-hadoop-terasort
+++ b/magpie-run-hadoop-terasort
@@ -109,6 +109,12 @@ then
     $command
 fi
 
+if ${hadoopcmdprefix}/hadoop fs -ls ${pathprefix} | grep -q terasort-validate
+then
+    command="${hadoopcmdprefix}/hadoop fs ${rmoption} ${pathprefix}terasort-validate"
+    $command
+fi
+
 if [ "${HADOOP_TERAGEN_MAP_COUNT:-0}" -ne "0" ]
 then
     mtasks=$HADOOP_TERAGEN_MAP_COUNT
@@ -138,9 +144,9 @@ sleep 30
 	    
 if [ "${HADOOP_TERASORT_REDUCER_COUNT:-0}" -ne "0" ]
 then
-    rtasks=$HADOOP_TERASORT_REDUCER_COUNT
+    sortreducetasks=$HADOOP_TERASORT_REDUCER_COUNT
 else
-    rtasks=`expr $HADOOP_SLAVE_COUNT \* 2`
+    sortreducetasks=`expr $HADOOP_SLAVE_COUNT \* 2`
 fi
 
 if [ "${HADOOP_TERASORT_OUTPUT_REPLICATION}X" != "X" ]
@@ -148,14 +154,44 @@ then
     replicationcount="-Dmapreduce.terasort.output.replication=${HADOOP_TERASORT_OUTPUT_REPLICATION}"
 fi
 
-command="${hadoopcmdprefix}/hadoop jar ${terasortexamples} terasort ${extralibjars} -Dmapred.reduce.tasks=$rtasks ${replicationcount} ${clearcache} ${pathprefix}terasort-teragen ${pathprefix}terasort-sort"
+command="${hadoopcmdprefix}/hadoop jar ${terasortexamples} terasort ${extralibjars} -Dmapred.reduce.tasks=$sortreducetasks ${replicationcount} ${clearcache} ${pathprefix}terasort-teragen ${pathprefix}terasort-sort"
 
 echo "Running $command" >&2
 $command
+
+if [ "${HADOOP_TERASORT_RUN_TERAVALIDATE}" == "yes" ]
+then
+    sleep 30
+
+    # I assume no user is concerned with performance here, we just go with this fixed number 
+    validatereducetasks=`expr $HADOOP_SLAVE_COUNT`
+
+    command="${hadoopcmdprefix}/hadoop jar ${terasortexamples} teravalidate ${extralibjars} -Dmapred.reduce.tasks=$validatereducetasks ${pathprefix}terasort-sort ${pathprefix}terasort-validate"
+
+    echo "Running $command" >&2
+    $command
+
+    validateerrors=`${hadoopcmdprefix}/hadoop fs -cat ${pathprefix}terasort-validate/part-r-00000 | grep error | wc -l`
+
+    if [ "${validateerrors}" != "0" ]
+    then
+	echo "TeraValidate Result: Errors in terasort output"
+    else
+	echo "TeraValidate Result: No errors in terasort output"
+    fi
+
+    outputchecksum=`${hadoopcmdprefix}/hadoop fs -cat ${pathprefix}terasort-validate/part-r-00000 | head -n 1 | awk '{print $2}'`
+    echo "TeraValidate Checksum: ${outputchecksum}"
+fi
 
 command="${hadoopcmdprefix}/hadoop fs ${rmoption} ${pathprefix}terasort-teragen"
 $command
 command="${hadoopcmdprefix}/hadoop fs ${rmoption} ${pathprefix}terasort-sort"
 $command
+if [ "${HADOOP_TERASORT_RUN_TERAVALIDATE}" == "yes" ]
+then
+    command="${hadoopcmdprefix}/hadoop fs ${rmoption} ${pathprefix}terasort-validate"
+    $command
+fi
 
 exit 0
