Support Hadoop mode 'upgradehdfs' to allow for HDFS upgrades

diff --git a/magpie-check-inputs b/magpie-check-inputs
--- a/magpie-check-inputs
+++ b/magpie-check-inputs
@@ -392,9 +392,10 @@ then
     if [ "${HADOOP_MODE}" != "terasort" ] \
 	&& [ "${HADOOP_MODE}" != "script" ] \
 	&& [ "${HADOOP_MODE}" != "interactive" ] \
+	&& [ "${HADOOP_MODE}" != "upgradehdfs" ] \
 	&& [ "${HADOOP_MODE}" != "setuponly" ]
     then
-	echo "HADOOP_MODE must be set to terasort, script, interactive, setuponly"
+	echo "HADOOP_MODE must be set to terasort, script, interactive, upgradehdfs, or setuponly"
 	exit 1
     fi
 
@@ -437,6 +438,27 @@ then
 	fi
     fi
 
+    if [ "${MAGPIE_JOB_TYPE}" == "hadoop" ] && [ "${HADOOP_MODE}" == "upgradehdfs" ]
+    then
+	if [ "${HADOOP_VERSION}X" == "X" ]
+	then
+	    echo "HADOOP_VERSION must be set for HADOOP_MODE = ${HADOOP_MODE}"
+	    exit 1
+	fi
+
+	if ! echo ${HADOOP_VERSION} | grep -q -E "[2-9]\.[2-9]\.[0-9]"
+	then 
+	    echo "HADOOP_MODE of ${HADOOP_MODE} only supported in Hadoop 2.2.0 and more recent versions"
+	    exit 1
+	fi
+
+	if [ ! -f "${MAGPIE_SCRIPTS_HOME}/magpie-run-hadoop-upgradehdfs" ]
+	then
+	    echo "${MAGPIE_SCRIPTS_HOME}/magpie-run-hadoop-upgradehdfs cannot be found, it is required for HADOOP_MODE = ${HADOOP_MODE}"
+	    exit 1
+	fi
+    fi
+
     if [ "${HADOOP_FILESYSTEM_MODE}" != "hdfs" ] \
 	&& [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsoverlustre" ] \
 	&& [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsovernetworkfs" ] \
@@ -455,6 +477,16 @@ then
         && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsovernetworkfs" ])
     then
 	echo "HADOOP_SETUP_TYPE of ${HADOOP_SETUP_TYPE} must be set with HADOOP_FILESYSTEM_MODE of hdfs, hdfsoverlustre, or hdfsovernetworkfs"
+	exit 1
+    fi
+
+    if [ "${MAGPIE_JOB_TYPE}" == "hadoop" ] \
+	&& [ "${HADOOP_MODE}" == "upgradehdfs" ] \
+	&& [ "${HADOOP_FILESYSTEM_MODE}" != "hdfs" ] \
+        && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsoverlustre" ] \
+        && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsovernetworkfs" ]
+    then
+	echo "HADOOP_MODE of ${HADOOP_MODE} only supported with HADOOP_FILESYSTEM_MODE of hdfs, hdfsoverlustre, or hdfsovernetworkfs"
 	exit 1
     fi
 
