Rename magpie-run-interactive-mode to magpie-run-job-wait-mode
Re-use magpie-run-job-wait-mode to be able to handle 'launch'
and 'server' mode in magpie-run.

diff --git a/magpie-run-job-wait-mode b/magpie-run-job-wait-mode
--- a/magpie-run-job-wait-mode
+++ b/magpie-run-job-wait-mode
@@ -22,9 +22,9 @@
 #  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
 #############################################################################
 
-# This script is for interactive mode.  For the most part, it
-# shouldn't be editted.  See job submission files for configuration
-# details.
+# This script is for managing scripts that are run.  For the most
+# part, it shouldn't be editted.  See job submission files for
+# configuration details.
 
 source ${MAGPIE_SCRIPTS_HOME}/magpie-common-exports
 source ${MAGPIE_SCRIPTS_HOME}/magpie-common-functions
@@ -33,18 +33,38 @@ source ${MAGPIE_SCRIPTS_HOME}/magpie-variable-conversion
 # For this run, we will use cluster specific paths
 Magpie_make_all_local_dirs_node_specific
 
+if [ "$1X" == "X" ]
+then
+    echo "Internal error - magpie-job-wait-mode, first argument unset"
+    exit 1
+fi
+
+if [ "$1" != "interactive" ] && [ "$1" != "launch" ] && [ "$1" != "server" ]
+then
+    echo "Internal error - magpie-job-wait-mode, first argument invalid = $1"
+    exit 1
+fi
+
+jobwaittype=$1
+
 mypid=$$
 
-${MAGPIE_SCRIPTS_HOME}/magpie-run-sleep countdown &
-childpid=$!
+if [ "${jobwaittype}" == "interactive" ]
+then
+    ${MAGPIE_SCRIPTS_HOME}/magpie-run-sleep countdown &
+    childpid=$!
+else
+    ${MAGPIE_SCRIPTS_HOME}/magpie-run-sleep normal &
+    childpid=$!
+fi
 
 # Some systems have SIGUSR1 as USR1 so we hardcode the value of 10
 
 echo "*******************************************************"
-echo "* Run '${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} $(hostname) kill -s 10 ${mypid}' to exit 'interactive' mode early."
+echo "* Run '${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} $(hostname) kill -s 10 ${mypid}' to exit '${jobwaittype}' mode early."
 echo "*******************************************************"
 
-trap "echo \"Received interrupt from user, interactive mode ending early.\"; kill -s 9 ${childpid}" 10
+trap "echo \"Received interrupt from user, ${jobwaittype} mode ending early.\"; kill -s 9 ${childpid}" 10
 
 wait $childpid
 
@@ -53,6 +73,6 @@ childstatus=$?
 if [ "${childstatus}" == "0" ]
 then
     echo "*******************************************************"
-    echo "* End of interactive mode"
+    echo "* End of '${jobwaittype}' mode"
     echo "*******************************************************"
 fi
