Support Zookeeper in Magpie

diff --git a/magpie-setup b/magpie-setup
--- a/magpie-setup
+++ b/magpie-setup
@@ -38,6 +38,10 @@ fi
 
 source ${MAGPIE_SCRIPTS_HOME}/magpie-common-exports
 
+#
+# Setup Hadoop directories
+#
+
 mkdir -p $HADOOP_LOCAL_JOB_DIR
 if [ $? -ne 0 ] ; then
     echo "mkdir failed making ${HADOOP_LOCAL_JOB_DIR}"
@@ -59,6 +63,35 @@ fi
 export YARN_CONF_DIR=${HADOOP_CONF_DIR}
 export YARN_LOG_DIR=${HADOOP_LOG_DIR}
 
+#
+# Setup Zookeeper directories
+#
+
+if [ "${ZOOKEEPER_SETUP}" == "yes" ]
+then
+    mkdir -p $ZOOKEEPER_LOCAL_JOB_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${ZOOKEEPER_LOCAL_JOB_DIR}"
+	exit 1
+    fi
+    
+    mkdir -p $ZOOKEEPER_CONF_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${ZOOKEEPER_CONF_DIR}"
+	exit 1
+    fi
+
+    mkdir -p $ZOOKEEPER_LOG_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${ZOOKEEPER_LOG_DIR}"
+	exit 1
+    fi
+fi
+
+#
+# Setup/Calculate Hadoop Config
+#
+
 # Create master and slave files
 
 hash hostlist 2>/dev/null
@@ -78,7 +111,27 @@ else
 fi
 
 ${hostrangescript} ${hostrangescriptoptions} ${SLURM_JOB_NODELIST} | head -1 > ${HADOOP_CONF_DIR}/masters
-${hostrangescript} ${hostrangescriptoptions} ${SLURM_JOB_NODELIST} | tail -n+2 > ${HADOOP_CONF_DIR}/slaves
+${hostrangescript} ${hostrangescriptoptions} ${SLURM_JOB_NODELIST} | tail -n+2 > ${HADOOP_CONF_DIR}/tmp_slaves
+
+if [ "${ZOOKEEPER_SETUP}" == "yes" ]
+then
+    tmpslavecount=`cat ${HADOOP_CONF_DIR}/tmp_slaves | wc -l`
+    hadoopslavecount=`expr ${tmpslavecount} - ${ZOOKEEPER_REPLICATION_COUNT}`
+    zookeeperslavestart=`expr ${hadoopslavecount} + 1`
+
+    if [ "${ZOOKEEPER_SHARE_NODES}" != "yes" ] 
+    then
+	head -${hadoopslavecount} ${HADOOP_CONF_DIR}/tmp_slaves > ${HADOOP_CONF_DIR}/slaves
+	tail -n+${zookeeperslavestart} ${HADOOP_CONF_DIR}/tmp_slaves > ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves 
+    else
+	cp ${HADOOP_CONF_DIR}/tmp_slaves ${HADOOP_CONF_DIR}/slaves
+	tail -n+${zookeeperslavestart} ${HADOOP_CONF_DIR}/tmp_slaves > ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves 
+    fi
+else
+    cp ${HADOOP_CONF_DIR}/tmp_slaves ${HADOOP_CONF_DIR}/slaves
+fi
+
+rm -f ${HADOOP_CONF_DIR}/tmp_slaves
 
 export HADOOP_MASTER_NODE=`head -1 ${HADOOP_CONF_DIR}/masters`
 
@@ -257,7 +310,7 @@ if [ ${reducecontainermb} -gt ${yarnmaxcontainer} ]
 then
     yarnmaxcontainer=${reducecontainermb}
 fi
- 
+
 if [ "${HADOOP_MAPREDUCE_SLOWSTART}X" != "X" ]
 then
     mapredslowstart=${HADOOP_MAPREDUCE_SLOWSTART}
@@ -433,7 +486,7 @@ else
 fi
 
 #
-# Setup file system
+# Setup Hadoop file system
 #
 
 pathcount=0
@@ -667,6 +720,65 @@ else
 fi
 
 #
+# Setup/Calculate Zookeeper Config
+#
+
+if [ "${ZOOKEEPER_SETUP}" == "yes" ]
+then
+    myhostname=`hostname`
+    if [ $(grep -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves) ]
+    then
+	zookeepernoderank=`grep -n -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves | awk --field-separator=':' '{print $1}'`
+	
+	if [ "${ZOOKEEPER_FILESYSTEM_MODE}" == "networkfs" ]
+	then
+            # Setup node directory per node 
+            zookeeperdatadirpathtmp="${ZOOKEEPER_DATA_DIR}/node-${zookeepernoderank}"
+            zookeeperdatadirpath=`echo "${zookeeperdatadirpathtmp}" | sed "s/\\//\\\\\\\\\//g"`
+            
+            mkdir -p ${zookeeperdatadirpathtmp}
+            if [ $? -ne 0 ] ; then
+		echo "mkdir failed making ${zookeeperdatadirpathtmp}"
+		exit 1
+            fi
+	elif [ "${ZOOKEEPER_FILESYSTEM_MODE}" == "local" ]
+	then
+            zookeeperdatadirpathtmp="${ZOOKEEPER_DATA_DIR}"
+            zookeeperdatadirpath=`echo "${zookeeperdatadirpathtmp}" | sed "s/\\//\\\\\\\\\//g"`
+            
+            mkdir -p ${zookeeperdatadirpathtmp}
+            if [ $? -ne 0 ] ; then
+		echo "mkdir failed making ${zookeeperdatadirpathtmp}"
+		exit 1
+            fi
+	fi
+	
+	echo "${zookeepernoderank}" > ${zookeeperdatadirpathtmp}/myid
+
+	if [ "${ZOOKEEPER_TICKTIME}X" != "X" ]
+	then
+	    zookeeperticktime=${ZOOKEEPER_TICKTIME}
+	else
+	    zookeeperticktime=2000
+	fi
+
+	if [ "${ZOOKEEPER_INITLIMIT}X" != "X" ]
+	then
+	    zookeeperinitlimit=${ZOOKEEPER_INITLIMIT}
+	else
+	    zookeeperinitlimit=10
+	fi
+
+	if [ "${ZOOKEEPER_SYNCLIMIT}X" != "X" ]
+	then
+	    zookeepersynclimit=${ZOOKEEPER_SYNCLIMIT}
+	else
+	    zookeepersynclimit=5
+	fi
+    fi
+fi
+
+#
 # Get config files for setup
 #
 
@@ -675,6 +787,13 @@ then
     hadoopconffiledir=${MAGPIE_SCRIPTS_HOME}/conf
 else
     hadoopconffiledir=${HADOOP_CONF_FILES}
+fi
+
+if [ "${ZOOKEEPER_CONF_FILES}X" == "X" ]
+then
+    zookeeperconffiledir=${MAGPIE_SCRIPTS_HOME}/conf
+else
+    zookeeperconffiledir=${ZOOKEEPER_CONF_FILES}
 fi
 
 if [ ${HADOOP_SETUP_TYPE} == "MR1" ]
@@ -696,8 +815,11 @@ else
     exit 1
 fi
 
+zookeepercfg=${zookeeperconffiledir}/zoo.cfg
+zookeeperenvsh=${zookeeperconffiledir}/zookeeper-env.sh
+
 #
-# Setup configuration files and environment files
+# Setup Hadoop configuration files and environment files
 #
 
 if [ ${HADOOP_SETUP_TYPE}  == "MR1" ] \
@@ -705,7 +827,7 @@ if [ ${HADOOP_SETUP_TYPE}  == "MR1" ] \
 then
 
     sed -e "s/HADOOPTMPDIR/${hadooptmpdir}/g" \
-	-e "s/FSDEFAULT/${fsdefault}/g" \
+               	-e "s/FSDEFAULT/${fsdefault}/g" \
 	-e "s/IOBUFFERSIZE/${iobuffersize}/g" \
 	-e "s/LOCALBLOCKSIZE/${rawnetworkfsblocksize}/g" \
 	-e "s/INTELLUSTREROOTDIR/${intellustrerootdir}/g" \
@@ -766,10 +888,10 @@ then
 
     cat ${hadoopconffiledir}/hadoop.log4j.properties > ${HADOOP_CONF_DIR}/log4j.properties
 fi
-    
+
 if [ ${HADOOP_SETUP_TYPE}  == "MR2" ]
 then
-	sed -e "s/HADOOP_MASTER_HOST/${HADOOP_MASTER_NODE}/g" \
+    sed -e "s/HADOOP_MASTER_HOST/${HADOOP_MASTER_NODE}/g" \
 	-e "s/YARNMINCONTAINER/${yarnmincontainer}/g" \
 	-e "s/YARNMAXCONTAINER/${yarnmaxcontainer}/g" \
 	-e "s/YARNRESOURCEMEMORY/${yarnresourcememory}/g" \
@@ -815,6 +937,43 @@ then
 	-e "s/HADOOPHOSTSEXCLUDEFILENAME/${hostsexcludefile}/g" \
 	-e "s/DFSDATANODEDIR/${datanodedir}/g" \
 	$hdfssitexml > ${HADOOP_CONF_DIR}/hdfs-site.xml
+fi
+
+#
+# Setup Zookeeper configuration files and environment files
+#
+
+if [ "${ZOOKEEPER_SETUP}" == "yes" ]
+then
+    myhostname=`hostname`
+    if [ $(grep -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves) ]
+    then
+	sed -e "s/ZOOKEEPERDATADIR/${zookeeperdatadirpath}/g" \
+	    -e "s/ZOOKEEPERTICKTIME/${zookeeperticktime}/g" \
+	    -e "s/ZOOKEEPERINITLIMIT/${zookeeperinitlimit}/g" \
+	    -e "s/ZOOKEEPERSYNCLIMIT/${zookeepersynclimit}/g" \
+            $zookeepercfg > ${ZOOKEEPER_CONF_DIR}/zoo.cfg
+
+	zookeepernodes=`cat ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves`
+	
+	servercount=1
+	for zookeepernode in ${zookeepernodes}
+	do
+            echo "server.${servercount}=${zookeepernode}:2888:3888" >> ${ZOOKEEPER_CONF_DIR}/zoo.cfg
+            servercount=$((servercount+1))
+	done
+	
+	zookeeperjavahomesubst=`echo "${JAVA_HOME}" | sed "s/\\//\\\\\\\\\//g"`
+	zookeeperlogdirsubst=`echo "${ZOOKEEPER_LOG_DIR}" | sed "s/\\//\\\\\\\\\//g"`
+	zookeeperconfdirsubst=`echo "${ZOOKEEPER_CONF_DIR}" | sed "s/\\//\\\\\\\\\//g"`
+
+	sed -e "s/MAGPIEJAVAHOME/${zookeeperjavahomesubst}/g" \
+	    -e "s/ZOOKEEPERLOGDIR/${zookeeperlogdirsubst}/g" \
+	    -e "s/ZOOKEEPERCONFDIR/${zookeeperconfdirsubst}/g" \
+	    $zookeeperenvsh > ${ZOOKEEPER_CONF_DIR}/zookeeper-env.sh
+
+	cat ${zookeeperconffiledir}/zookeeper.log4j.properties > ${ZOOKEEPER_CONF_DIR}/log4j.properties
+    fi
 fi
 
 #
