Support HADOOP_HDFSOVERLUSTRE_REMOVE_LOCKS and HADOOP_HDFSOVERNETWORKFS_REMOVE_LOCKS, ability to cleanup lock files in HDFS if necessary.

diff --git a/magpie-setup-hadoop b/magpie-setup-hadoop
--- a/magpie-setup-hadoop
+++ b/magpie-setup-hadoop
@@ -542,6 +542,17 @@ then
     fi
     
     pathcount=1
+
+    # Cleanup locks if requested
+    if ([ "${HADOOP_FILESYSTEM_MODE}" == "hdfsoverlustre" ] && [ "${HADOOP_HDFSOVERLUSTRE_REMOVE_LOCKS}" == "yes" ]) \
+	|| ([ "${HADOOP_FILESYSTEM_MODE}" == "hdfsovernetworkfs" ] && [ "${HADOOP_HDFSOVERNETWORKFS_REMOVE_LOCKS}" == "yes" ])
+    then
+	for num in `seq 0 ${HADOOP_SLAVE_COUNT}`
+	do
+	    lockfile="${HADOOP_HDFSOVERLUSTRE_PATH}/node-${num}/dfs/data/in_use.lock"
+	    rm -f ${lockfile}
+	done
+    fi
 elif [ "${HADOOP_FILESYSTEM_MODE}" == "rawnetworkfs" ]
 then
     hadooptmpdirsubst=`echo "${hadooptmpdir}" | sed "s/\\//\\\\\\\\\//g"`
