Various minor cleanup/re-org

diff --git a/magpie-setup-core b/magpie-setup-core
--- a/magpie-setup-core
+++ b/magpie-setup-core
@@ -85,31 +85,6 @@ then
 fi
 
 #
-# Setup Zookeeper directories
-#
-
-if [ "${ZOOKEEPER_SETUP}" == "yes" ]
-then
-    mkdir -p $ZOOKEEPER_LOCAL_JOB_DIR
-    if [ $? -ne 0 ] ; then
-	echo "mkdir failed making ${ZOOKEEPER_LOCAL_JOB_DIR}"
-	exit 1
-    fi
-    
-    mkdir -p $ZOOKEEPER_CONF_DIR
-    if [ $? -ne 0 ] ; then
-	echo "mkdir failed making ${ZOOKEEPER_CONF_DIR}"
-	exit 1
-    fi
-
-    mkdir -p $ZOOKEEPER_LOG_DIR
-    if [ $? -ne 0 ] ; then
-	echo "mkdir failed making ${ZOOKEEPER_LOG_DIR}"
-	exit 1
-    fi
-fi
-
-#
 # Setup Hbase directories
 #
 
@@ -180,6 +155,31 @@ then
     mkdir -p $STORM_LOG_DIR
     if [ $? -ne 0 ] ; then
 	echo "mkdir failed making ${STORM_LOG_DIR}"
+	exit 1
+    fi
+fi
+
+#
+# Setup Zookeeper directories
+#
+
+if [ "${ZOOKEEPER_SETUP}" == "yes" ]
+then
+    mkdir -p $ZOOKEEPER_LOCAL_JOB_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${ZOOKEEPER_LOCAL_JOB_DIR}"
+	exit 1
+    fi
+    
+    mkdir -p $ZOOKEEPER_CONF_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${ZOOKEEPER_CONF_DIR}"
+	exit 1
+    fi
+
+    mkdir -p $ZOOKEEPER_LOG_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${ZOOKEEPER_LOG_DIR}"
 	exit 1
     fi
 fi
