Add Mahout Support w/ Hadoop

diff --git a/magpie-setup-core b/magpie-setup-core
--- a/magpie-setup-core
+++ b/magpie-setup-core
@@ -95,6 +95,25 @@ then
 fi
 
 #
+# Setup Mahout directories
+#
+
+if [ "${MAHOUT_SETUP}" == "yes" ]
+then
+    mkdir -p $MAHOUT_CONF_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${MAHOUT_CONF_DIR}"
+	exit 1
+    fi
+
+    mkdir -p $MAHOUT_LOCAL_SCRATCH_DIR
+    if [ $? -ne 0 ] ; then
+	echo "mkdir failed making ${MAHOUT_LOCAL_SCRATCH_DIR}"
+	exit 1
+    fi
+fi
+
+#
 # Setup Hbase directories
 #
 
diff --git a/magpie-variable-conversion b/magpie-variable-conversion
--- a/magpie-variable-conversion
+++ b/magpie-variable-conversion
@@ -128,6 +128,37 @@ Magpie_make_pig_local_dirs_node_specific () {
     Magpie_make_pig_local_dirs "specific"
 }
 
+Magpie_make_mahout_local_dirs () {
+    which=$1
+
+    if [ "${MAHOUT_SETUP}" == "yes" ]
+    then
+	if [ "${MAHOUT_LOCAL_JOB_DIR}X" == "X" ]
+	then
+	    echo "Fatal error, Magpie_make_mahout_local_dirs called without MAHOUT_LOCAL_JOB_DIR set"
+	    exit 1
+	fi
+
+	export MAHOUT_CONF_DIR=${MAHOUT_LOCAL_JOB_DIR}/conf
+	export MAHOUT_LOCAL_SCRATCH_DIR=${MAHOUT_LOCAL_JOB_DIR}/scratch
+
+	if [ "${which}" == "specific" ]
+	then
+	    myhostname=`hostname`
+	    export MAHOUT_CONF_DIR=$(echo $MAHOUT_CONF_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g")
+	    export MAHOUT_LOCAL_SCRATCH_DIR=$(echo $MAHOUT_LOCAL_SCRATCH_DIR | sed "s/MAGPIEHOSTNAMESUBSTITUTION/${myhostname}/g")
+	fi
+    fi
+}
+
+Magpie_make_mahout_local_dirs_unspecified () {
+    Magpie_make_mahout_local_dirs "generic"
+}
+
+Magpie_make_mahout_local_dirs_node_specific () {
+    Magpie_make_mahout_local_dirs "specific"
+}
+
 Magpie_make_hbase_local_dirs () {
     which=$1
 
