Re-work code to get tool-rank-id from masters/slaves files instead of cluster noderank

diff --git a/magpie-setup b/magpie-setup
--- a/magpie-setup
+++ b/magpie-setup
@@ -551,63 +551,91 @@ then
 elif [ "${HADOOP_FILESYSTEM_MODE}" == "hdfsoverlustre" ]
 then
     # Setup node directory per node 
-    fspath="${HADOOP_HDFSOVERLUSTRE_PATH}/node-${MAGPIE_CLUSTER_NODERANK}"
-    hadooptmpdir=`echo "${fspath}" | sed "s/\\//\\\\\\\\\//g"`
-    fsdefault=`echo "hdfs://${HADOOP_MASTER_NODE}:54310" | sed "s/\\//\\\\\\\\\//g"`
-
-    # Assume if path doesn't exist must format
-    if [ -d "${fspath}" ]
+    myhostname=`hostname`
+    if [ $(grep -E "^${myhostname}$" ${HADOOP_CONF_DIR}/slaves) ] \
+	|| [ $(grep -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters) ]
     then
-	format=0
-    else
-	format=1
-	mkdir -p ${fspath}
-	if [ $? -ne 0 ] ; then
-	    echo "mkdir failed making ${fspath}"
-	    exit 1
+	if [ $(grep -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters) ]
+	then
+	    hadoopnoderank=0
+	else
+	    hadoopnoderank=`grep -n -E "^${myhostname}$" ${HADOOP_CONF_DIR}/slaves | awk --field-separator=':' '{print $1}'`
 	fi
-	/usr/bin/lfs setstripe --size ${hdfsblocksize} --count 1 ${fspath}
+
+	fspath="${HADOOP_HDFSOVERLUSTRE_PATH}/node-${hadoopnoderank}"
+	hadooptmpdir=`echo "${fspath}" | sed "s/\\//\\\\\\\\\//g"`
+	fsdefault=`echo "hdfs://${HADOOP_MASTER_NODE}:54310" | sed "s/\\//\\\\\\\\\//g"`
+	
+        # Assume if path doesn't exist must format
+	if [ -d "${fspath}" ]
+	then
+	    format=0
+	else
+	    format=1
+	    mkdir -p ${fspath}
+	    if [ $? -ne 0 ] ; then
+		echo "mkdir failed making ${fspath}"
+		exit 1
+	    fi
+	    /usr/bin/lfs setstripe --size ${hdfsblocksize} --count 1 ${fspath}
+	fi
+
+	if [ ${HADOOP_SETUP_TYPE} == "MR1" ]
+	then
+	    datanodedir="$\{hadoop.tmp.dir\}\/dfs\/data"
+	elif [ ${HADOOP_SETUP_TYPE}  == "MR2" ]
+	then
+	    datanodedir="file:\/\/\$\{hadoop.tmp.dir\}\/dfs\/data"
+	fi
+
+	pathcount=1
+    else
+	format=0 
+	pathcount=0
     fi
-
-    if [ ${HADOOP_SETUP_TYPE} == "MR1" ]
-    then
-	datanodedir="$\{hadoop.tmp.dir\}\/dfs\/data"
-    elif [ ${HADOOP_SETUP_TYPE}  == "MR2" ]
-    then
-	datanodedir="file:\/\/\$\{hadoop.tmp.dir\}\/dfs\/data"
-    fi
-
-    pathcount=1
-
 elif [ "${HADOOP_FILESYSTEM_MODE}" == "rawnetworkfs" ]
 then
     # Setup node directory per node, still need for "local" files
-    fspath="${HADOOP_RAWNETWORKFS_PATH}"
-    pernodepath="${fspath}/node-${MAGPIE_CLUSTER_NODERANK}"
-    hadooptmpdir=`echo "${pernodepath}" | sed "s/\\//\\\\\\\\\//g"`
-    fsdefault=`echo "file:///" | sed "s/\\//\\\\\\\\\//g"`
-
-    if [ ! -d "${fspath}" ]
+    myhostname=`hostname`
+    if [ $(grep -E "^${myhostname}$" ${HADOOP_CONF_DIR}/slaves) ] \
+	|| [ $(grep -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters) ]
     then
-        mkdir -p ${fspath}
-        if [ $? -ne 0 ] ; then
-            echo "mkdir failed making ${fspath}"
-            exit 1
-        fi
+	if [ $(grep -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters) ]
+	then
+	    hadoopnoderank=0
+	else
+	    hadoopnoderank=`grep -n -E "^${myhostname}$" ${HADOOP_CONF_DIR}/slaves | awk --field-separator=':' '{print $1}'`
+	fi
+
+	fspath="${HADOOP_RAWNETWORKFS_PATH}"
+	pernodepath="${fspath}/node-${hadoopnoderank}"
+	hadooptmpdir=`echo "${pernodepath}" | sed "s/\\//\\\\\\\\\//g"`
+	fsdefault=`echo "file:///" | sed "s/\\//\\\\\\\\\//g"`
+	
+	if [ ! -d "${fspath}" ]
+	then
+            mkdir -p ${fspath}
+            if [ $? -ne 0 ] ; then
+		echo "mkdir failed making ${fspath}"
+		exit 1
+            fi
+	fi
+	
+	if [ ! -d "${pernodepath}" ]
+	then
+            mkdir -p ${pernodepath}
+            if [ $? -ne 0 ] ; then
+		echo "mkdir failed making ${pernodepath}"
+		exit 1
+            fi
+	fi
+
+	format=0
+	pathcount=1
+    else
+	format=0
+	pathcount=0
     fi
-
-    if [ ! -d "${pernodepath}" ]
-    then
-        mkdir -p ${pernodepath}
-        if [ $? -ne 0 ] ; then
-            echo "mkdir failed making ${pernodepath}"
-            exit 1
-        fi
-    fi
-
-    format=0
-
-    pathcount=1
 elif [ "${HADOOP_FILESYSTEM_MODE}" == "intellustre" ]
 then
     # Setup node directory per node, still need for "local" files
@@ -632,33 +660,47 @@ then
 elif [ "${HADOOP_FILESYSTEM_MODE}" == "magpienetworkfs" ]
 then
     # Setup node directory per node, still need for "local" files
-    fspath="${HADOOP_MAGPIENETWORKFS_PATH}"
-    pernodepath="${fspath}/node-${MAGPIE_CLUSTER_NODERANK}"
-    hadooptmpdir=`echo "${pernodepath}" | sed "s/\\//\\\\\\\\\//g"`
-    fsdefault=`echo "magpienetworkfs:///" | sed "s/\\//\\\\\\\\\//g"`
-    magpienetworkfsbase=`echo "${fspath}" | sed "s/\\//\\\\\\\\\//g"`
-
-    if [ ! -d "${fspath}" ]
+    myhostname=`hostname`
+    if [ $(grep -E "^${myhostname}$" ${HADOOP_CONF_DIR}/slaves) ] \
+	|| [ $(grep -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters) ]
     then
-        mkdir -p ${fspath}
-        if [ $? -ne 0 ] ; then
-            echo "mkdir failed making ${fspath}"
-            exit 1
-        fi
+	if [ $(grep -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters) ]
+	then
+	    hadoopnoderank=0
+	else
+	    hadoopnoderank=`grep -n -E "^${myhostname}$" ${HADOOP_CONF_DIR}/slaves | awk --field-separator=':' '{print $1}'`
+	fi
+
+	fspath="${HADOOP_MAGPIENETWORKFS_PATH}"
+	pernodepath="${fspath}/node-${hadoopnoderank}"
+	hadooptmpdir=`echo "${pernodepath}" | sed "s/\\//\\\\\\\\\//g"`
+	fsdefault=`echo "magpienetworkfs:///" | sed "s/\\//\\\\\\\\\//g"`
+	magpienetworkfsbase=`echo "${fspath}" | sed "s/\\//\\\\\\\\\//g"`
+	
+	if [ ! -d "${fspath}" ]
+	then
+            mkdir -p ${fspath}
+            if [ $? -ne 0 ] ; then
+		echo "mkdir failed making ${fspath}"
+		exit 1
+            fi
+	fi
+
+	if [ ! -d "${pernodepath}" ]
+	then
+            mkdir -p ${pernodepath}
+            if [ $? -ne 0 ] ; then
+		echo "mkdir failed making ${pernodepath}"
+		exit 1
+            fi
+	fi
+
+	format=0
+	pathcount=1
+    else
+	format=0
+	pathcount=0
     fi
-
-    if [ ! -d "${pernodepath}" ]
-    then
-        mkdir -p ${pernodepath}
-        if [ $? -ne 0 ] ; then
-            echo "mkdir failed making ${pernodepath}"
-            exit 1
-        fi
-    fi
-
-    format=0
-
-    pathcount=1
 else
     echo "Illegal HADOOP_FILESYSTEM_MODE \"${HADOOP_FILESYSTEM_MODE}\" specified"
     exit 1
@@ -990,8 +1032,9 @@ fi
 
 if [ "${format}" -eq "1" ]
 then
-    # Only MAGPIE_CLUSTER_NODERANK 0 will format the node
-    if [ "$MAGPIE_CLUSTER_NODERANK" -eq "0" ]
+    # Only master will format the node
+    myhostname=`hostname`
+    if [ $(grep -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters) ]
     then
 	cd $HADOOP_HOME
 	echo 'Y' | bin/hadoop namenode -format
