Support ability to end job script early through similar kill mechanism.
Kill user job via sigusr2 signal, so timeout trap can be captured

diff --git a/magpie-run-job-wait-mode b/magpie-run-job-wait-mode
--- a/magpie-run-job-wait-mode
+++ b/magpie-run-job-wait-mode
@@ -39,7 +39,7 @@ then
     exit 1
 fi
 
-if [ "$1" != "interactive" ] && [ "$1" != "launch" ] && [ "$1" != "server" ]
+if [ "$1" != "interactive" ] && [ "$1" != "launch" ] && [ "$1" != "server" ] && [ "$1" != "script" ]
 then
     echo "Internal error - magpie-job-wait-mode, first argument invalid = $1"
     exit 1
@@ -47,24 +47,56 @@ fi
 
 jobwaittype=$1
 
+if [ "${jobwaittype}" == "script" ]
+then
+    if [ "$2X" == "X" ]
+    then
+	echo "Internal error - magpie-job-wait-mode, second argument unset"
+	exit 1
+    fi
+    scripttorun=$2
+fi
+
+
 mypid=$$
 
 if [ "${jobwaittype}" == "interactive" ]
 then
     ${MAGPIE_SCRIPTS_HOME}/magpie-run-sleep countdown &
     childpid=$!
-else
+    typemessage="'${jobwaittype}' mode"
+elif [ "${jobwaittype}" == "launch" ] || [ "${jobwaittype}" == "server" ]
+then
     ${MAGPIE_SCRIPTS_HOME}/magpie-run-sleep normal &
     childpid=$!
+    typemessage="'${jobwaittype}' mode"
+else
+    ${scripttorun} &
+    childpid=$!
+    typemessage="job"
 fi
 
 # Some systems have SIGUSR1 as USR1 so we hardcode the value of 10
 
 echo "*******************************************************"
-echo "* Run '${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} $(hostname) kill -s 10 ${mypid}' to exit '${jobwaittype}' mode early."
+echo "* Run '${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} $(hostname) kill -s 10 ${mypid}' to exit ${typemessage} early."
+if [ "${jobwaittype}" == "script" ]
+then
+    echo "*"
+    echo "* Warning: killing early may not kill jobs submitted to an internally"
+    echo "* managed scheduler within Magpie.  The job will be canceled during teardown"
+    echo "* of daemons.  Extraneous error messages from your job may occur until then."
+fi
 echo "*******************************************************"
 
-trap "echo \"Received interrupt from user, ${jobwaittype} mode ending early.\"; kill -s 9 ${childpid}" 10
+trap "echo \"Received interrupt from user, ${typemessage} ending early.\"; kill -s 9 ${childpid}" 10
+
+# Some systems have SIGUSR2 as USR2 so we hardcode the value of 12
+
+# This trap is used exclusively by Magpie to kill the job if it is
+# running long
+
+trap "echo \"Kill script due to job time limit being reached.\"; kill -s 9 ${childpid}" 12
 
 wait $childpid
 
@@ -73,6 +105,6 @@ childstatus=$?
 if [ "${childstatus}" == "0" ]
 then
     echo "*******************************************************"
-    echo "* End of '${jobwaittype}' mode"
+    echo "* End of ${typemessage}"
     echo "*******************************************************"
 fi
