Minor code cleanup in magpie-check-inputs

diff --git a/magpie-check-inputs b/magpie-check-inputs
--- a/magpie-check-inputs
+++ b/magpie-check-inputs
@@ -549,59 +549,56 @@ then
         fi
     fi
 
-    if [ "${HDFS_FEDERATION_NAMENODE_COUNT}X" != "X" ]
+    if [ "${HDFS_FEDERATION_NAMENODE_COUNT}X" != "X" ] && [ "${HDFS_FEDERATION_NAMENODE_COUNT}" -gt 1 ]
     then
-        if [ "${HDFS_FEDERATION_NAMENODE_COUNT}" -gt 1 ]
+        if ([ "${HADOOP_FILESYSTEM_MODE}" != "hdfs" ] \
+            && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsoverlustre" ] \
+            && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsovernetworkfs" ])
         then
-            if ([ "${HADOOP_FILESYSTEM_MODE}" != "hdfs" ] \
-                && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsoverlustre" ] \
-                && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsovernetworkfs" ])
+            echo "HDFS federation can only work with an HDFS based file system, cannot work with HADOOP_FILESYSTEM_MODE = ${HADOOP_FILESYSTEM_MODE}"
+            exit 1
+        fi
+
+        if ! echo ${HADOOP_VERSION} | grep -q -E "[2-9]\.[2-9]\.[0-9]"
+        then 
+            echo "HDFS Fderation only supported in Hadoop 2.2.0 and more recent versions"
+            exit 1
+        fi
+
+        # Ensure user listed atleast 1 mount for each namenode
+        for i in `seq 1 ${HDFS_FEDERATION_NAMENODE_COUNT}`
+        do
+            mountname="HDFS_FEDERATION_NAMENODE_${i}_MOUNT_1"
+            eval mountvalue="\$$mountname"
+            if [ "${mountvalue}X" == "X" ]
             then
-                echo "HDFS federation can only work with an HDFS based file system, cannot work with HADOOP_FILESYSTEM_MODE = ${HADOOP_FILESYSTEM_MODE}"
+                echo "HDFS federation requires atleast one mount specified for each namenode, ${mountname} must be specified" 
                 exit 1
             fi
+        done
 
-            if ! echo ${HADOOP_VERSION} | grep -q -E "[2-9]\.[2-9]\.[0-9]"
-            then 
-                echo "HDFS Fderation only supported in Hadoop 2.2.0 and more recent versions"
-                exit 1
-            fi
-
-            # Ensure user listed atleast 1 mount for each namenode
-            for i in `seq 1 ${HDFS_FEDERATION_NAMENODE_COUNT}`
+        # Check that all mounts are absolute paths
+        for i in `seq 1 ${HDFS_FEDERATION_NAMENODE_COUNT}`
+        do
+            j=1
+            while true;
             do
-                mountname="HDFS_FEDERATION_NAMENODE_${i}_MOUNT_1"
+                mountname="HDFS_FEDERATION_NAMENODE_${i}_MOUNT_${j}"
                 eval mountvalue="\$$mountname"
                 if [ "${mountvalue}X" == "X" ]
                 then
-                    echo "HDFS federation requires atleast one mount specified for each namenode, ${mountname} must be specified" 
+                    break;
+                fi
+                if [[ "${mountvalue}" != /* ]]
+                then
+                    echo "HDFS federation mount must be an absolute path beginning with a /"
                     exit 1
                 fi
+                j=`expr ${j} + 1`
             done
+        done 
 
-            # Check that all mounts are absolute paths
-            for i in `seq 1 ${HDFS_FEDERATION_NAMENODE_COUNT}`
-            do
-                j=1
-                while true;
-                do
-                    mountname="HDFS_FEDERATION_NAMENODE_${i}_MOUNT_${j}"
-                    eval mountvalue="\$$mountname"
-                    if [ "${mountvalue}X" == "X" ]
-                    then
-                        break;
-                    fi
-                    if [[ "${mountvalue}" != /* ]]
-                    then
-                        echo "HDFS federation mount must be an absolute path beginning with a /"
-                        exit 1
-                    fi
-                    j=`expr ${j} + 1`
-                done
-           done 
-
-            nodecount=`expr ${nodecount} - ${HDFS_FEDERATION_NAMENODE_COUNT-1}`
-        fi
+        nodecount=`expr ${nodecount} - ${HDFS_FEDERATION_NAMENODE_COUNT-1}`
     fi
 
     if [ "${HADOOP_MODE}" == "terasort" ]
