Merge magpie-run-sleep and magpie-run-countdown-sleep into one script with a required commandline argument option.

diff --git a/magpie-run-sleep b/magpie-run-sleep
--- a/magpie-run-sleep
+++ b/magpie-run-sleep
@@ -25,9 +25,10 @@
 # This script is for sleeping.  For the most part, it shouldn't be
 # editted.  See job submission files for configuration details.
 
-# Curious why I bother to write this script?  It's most for
-# refactoring.  If I put "sleeping" into this script, then interactive
-# mode and setuponly becomes just "another script".
+# Why did I bother to write this script?  It's most for refactoring.
+# If I put "sleeping" into a script, then things like 'interactive'
+# mode or 'setuponly' are just "another script" and be managed just
+# like running a script with actual code in it.
 
 source ${MAGPIE_SCRIPTS_HOME}/magpie-common-exports
 source ${MAGPIE_SCRIPTS_HOME}/magpie-common-functions
@@ -38,6 +39,68 @@ Magpie_make_all_local_dirs_node_specific
 
 # Will set jobtimeseconds
 Magpie_job_time_seconds
-sleep ${jobtimeseconds}
+
+secondsleft=$jobtimeseconds
+
+if [ "$1X" == "X" ]
+then
+    echo "Internal error - magpie-run-sleep, first argument unset"
+    exit 1
+fi
+
+if [ "$1" != "normal" ] && [ "$1" != "countdown" ]
+then
+    echo "Internal error - magpie-run-sleep, first argument invalid = $1"
+    exit 1
+fi
+
+sleeptype=$1
+
+if [ "${sleeptype}" == "normal" ]
+then
+    sleep ${secondsleft}
+else
+# 3600 = 60 mins
+    if [ "${secondsleft}" -gt 3600 ]
+    then
+	sleepseconds=`expr ${secondsleft} - 3600`
+	sleep ${sleepseconds}
+
+	echo "*** Warning - 60 minutes left"
+	secondsleft=3600
+    fi
+
+# 1800 = 30 mins 
+    if [ "${secondsleft}" -gt 1800 ]
+    then
+	sleepseconds=`expr ${secondsleft} - 1800`
+	sleep ${sleepseconds}
+
+	echo "*** Warning - 30 minutes left"
+	secondsleft=1800
+    fi
+
+# 300 = 5 mins 
+    if [ "${secondsleft}" -gt 300 ]
+    then
+	sleepseconds=`expr ${secondsleft} - 300`
+	sleep ${sleepseconds}
+
+	echo "*** Warning - 5 minutes left"
+	secondsleft=300
+    fi
+
+# 60 = 1 min 
+    if [ "${secondsleft}" -gt 60 ]
+    then
+	sleepseconds=`expr ${secondsleft} - 60`
+	sleep ${sleepseconds}
+
+	echo "*** Warning - 1 minute left"
+	secondsleft=60
+    fi
+
+    sleep ${secondsleft}
+fi
 
 exit 0
