Untabify all files for consistency across files

diff --git a/magpie-lib-core b/magpie-lib-core
--- a/magpie-lib-core
+++ b/magpie-lib-core
@@ -42,52 +42,52 @@ Magpie_am_I_master () {
 
     if [ "${HADOOP_SETUP}" == "yes" ] && [ -f "${HADOOP_CONF_DIR}/masters" ]
     then
-	if grep -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters
-	then 
-	    return 0
-	fi
+        if grep -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters
+        then 
+            return 0
+        fi
     elif [ "${HBASE_SETUP}" == "yes" ] && [ -f "${HBASE_CONF_DIR}/masters" ]
     then
-	if grep -q -E "^${myhostname}$" ${HBASE_CONF_DIR}/masters
-	then 
-	    return 0
-	fi
+        if grep -q -E "^${myhostname}$" ${HBASE_CONF_DIR}/masters
+        then 
+            return 0
+        fi
     elif [ "${SPARK_SETUP}" == "yes" ] && [ -f "${SPARK_CONF_DIR}/masters" ]
     then
-	if grep -q -E "^${myhostname}$" ${SPARK_CONF_DIR}/masters
-	then 
-	    return 0
-	fi
+        if grep -q -E "^${myhostname}$" ${SPARK_CONF_DIR}/masters
+        then 
+            return 0
+        fi
     elif [ "${STORM_SETUP}" == "yes" ] && [ -f "${STORM_CONF_DIR}/masters" ]
     then
-	if grep -q -E "^${myhostname}$" ${STORM_CONF_DIR}/masters
-	then 
-	    return 0
-	fi
+        if grep -q -E "^${myhostname}$" ${STORM_CONF_DIR}/masters
+        then 
+            return 0
+        fi
     elif [ "${ZOOKEEPER_SETUP}" == "yes" ] && [ -f "${ZOOKEEPER_CONF_DIR}/zookeeper_master" ]
     then
-	if grep -q -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_master
-	then 
-	    return 0
-	fi
+        if grep -q -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_master
+        then 
+            return 0
+        fi
     elif [ "${KAFKA_SETUP}" == "yes" ] && [ -f "${KAFKA_CONF_DIR}/masters" ]
     then
-	if grep -q -E "^${myhostname}$" ${KAFKA_CONF_DIR}/masters
-	then 
-	    return 0
-	fi
+        if grep -q -E "^${myhostname}$" ${KAFKA_CONF_DIR}/masters
+        then 
+            return 0
+        fi
     elif [ "${ZEPPELIN_SETUP}" == "yes" ] && [ -f "${ZEPPELIN_CONF_DIR}/masters" ]
     then
-	if grep -q -E "^${myhostname}$" ${ZEPPELIN_CONF_DIR}/masters
-	then 
-	    return 0
-	fi
+        if grep -q -E "^${myhostname}$" ${ZEPPELIN_CONF_DIR}/masters
+        then 
+            return 0
+        fi
     elif [ "${TACHYON_SETUP}" == "yes" ] && [ -f "${TACHYON_CONF_DIR}/masters" ]
     then
-	if grep -q -E "^${myhostname}$" ${TACHYON_CONF_DIR}/masters
-	then 
-	    return 0
-	fi
+        if grep -q -E "^${myhostname}$" ${TACHYON_CONF_DIR}/masters
+        then 
+            return 0
+        fi
     fi
     return 1
 }
@@ -98,20 +98,20 @@ Magpie_am_I_a_hadoop_node () {
     Magpie_make_hadoop_local_dirs_node_specific
 
     if grep -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/slaves \
-	|| grep -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters \
-	|| grep -s -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/namenode_hdfs_federation
+        || grep -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters \
+        || grep -s -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/namenode_hdfs_federation
     then 
-	if grep -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters
-	then
-	    hadoopnoderank=0
-	elif grep -s -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/namenode_hdfs_federation
-	then
-	    local subrank=`grep -n -E "^${myhostname}$" ${HADOOP_CONF_DIR}/namenode_hdfs_federation | awk --field-separator=':' '{print $1}'`
-	    hadoopnoderank="0${subrank}"
-	else
-	    hadoopnoderank=`grep -n -E "^${myhostname}$" ${HADOOP_CONF_DIR}/slaves | awk --field-separator=':' '{print $1}'`
-	fi
-	return 0
+        if grep -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters
+        then
+            hadoopnoderank=0
+        elif grep -s -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/namenode_hdfs_federation
+        then
+            local subrank=`grep -n -E "^${myhostname}$" ${HADOOP_CONF_DIR}/namenode_hdfs_federation | awk --field-separator=':' '{print $1}'`
+            hadoopnoderank="0${subrank}"
+        else
+            hadoopnoderank=`grep -n -E "^${myhostname}$" ${HADOOP_CONF_DIR}/slaves | awk --field-separator=':' '{print $1}'`
+        fi
+        return 0
     fi
     return 1
 }
@@ -122,16 +122,16 @@ Magpie_am_I_a_hadoop_namenode () {
     Magpie_make_hadoop_local_dirs_node_specific
 
     if grep -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters \
-	|| grep -s -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/namenode_hdfs_federation
+        || grep -s -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/namenode_hdfs_federation
     then 
-	if grep -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters
-	then
-	    hadoopnoderank=0
-	else
-	    local subrank=`grep -n -E "^${myhostname}$" ${HADOOP_CONF_DIR}/namenode_hdfs_federation | awk --field-separator=':' '{print $1}'`
-	    hadoopnoderank="0${subrank}"
-	fi
-	return 0
+        if grep -q -E "^${myhostname}$" ${HADOOP_CONF_DIR}/masters
+        then
+            hadoopnoderank=0
+        else
+            local subrank=`grep -n -E "^${myhostname}$" ${HADOOP_CONF_DIR}/namenode_hdfs_federation | awk --field-separator=':' '{print $1}'`
+            hadoopnoderank="0${subrank}"
+        fi
+        return 0
     fi
     return 1
 }
@@ -142,15 +142,15 @@ Magpie_am_I_a_hbase_node () {
     Magpie_make_hbase_local_dirs_node_specific
 
     if grep -q -E "^${myhostname}$" ${HBASE_CONF_DIR}/regionservers \
-	|| grep -q -E "^${myhostname}$" ${HBASE_CONF_DIR}/masters
+        || grep -q -E "^${myhostname}$" ${HBASE_CONF_DIR}/masters
     then 
-	if grep -q -E "^${myhostname}$" ${HBASE_CONF_DIR}/masters
-	then
-	    hbasenoderank=0
-	else
-	    hbasenoderank=`grep -n -E "^${myhostname}$" ${HBASE_CONF_DIR}/regionservers | awk --field-separator=':' '{print $1}'`
-	fi
-	return 0
+        if grep -q -E "^${myhostname}$" ${HBASE_CONF_DIR}/masters
+        then
+            hbasenoderank=0
+        else
+            hbasenoderank=`grep -n -E "^${myhostname}$" ${HBASE_CONF_DIR}/regionservers | awk --field-separator=':' '{print $1}'`
+        fi
+        return 0
     fi
     return 1
 }
@@ -165,15 +165,15 @@ Magpie_am_I_a_spark_node () {
     Magpie_make_spark_local_dirs_node_specific
 
     if grep -q -E "^${myhostname}$" ${SPARK_CONF_DIR}/slaves \
-	|| grep -q -E "^${myhostname}$" ${SPARK_CONF_DIR}/masters
+        || grep -q -E "^${myhostname}$" ${SPARK_CONF_DIR}/masters
     then 
-	if grep -q -E "^${myhostname}$" ${SPARK_CONF_DIR}/masters
-	then
-	    sparknoderank=0
-	else
-	    sparknoderank=`grep -n -E "^${myhostname}$" ${SPARK_CONF_DIR}/slaves | awk --field-separator=':' '{print $1}'`
-	fi
-	return 0
+        if grep -q -E "^${myhostname}$" ${SPARK_CONF_DIR}/masters
+        then
+            sparknoderank=0
+        else
+            sparknoderank=`grep -n -E "^${myhostname}$" ${SPARK_CONF_DIR}/slaves | awk --field-separator=':' '{print $1}'`
+        fi
+        return 0
     fi
     return 1
 }
@@ -184,15 +184,15 @@ Magpie_am_I_a_kafka_node () {
     Magpie_make_kafka_local_dirs_node_specific
 
     if grep -q -E "^${myhostname}$" ${KAFKA_CONF_DIR}/slaves \
-	|| grep -q -E "^${myhostname}$" ${KAFKA_CONF_DIR}/masters
+        || grep -q -E "^${myhostname}$" ${KAFKA_CONF_DIR}/masters
     then 
-	if grep -q -E "^${myhostname}$" ${KAFKA_CONF_DIR}/masters
-	then
-	    kafkanoderank=0
-	else
-	    kafkanoderank=`grep -n -E "^${myhostname}$" ${KAFKA_CONF_DIR}/slaves | awk --field-separator=':' '{print $1}'`
-	fi
-	return 0
+        if grep -q -E "^${myhostname}$" ${KAFKA_CONF_DIR}/masters
+        then
+            kafkanoderank=0
+        else
+            kafkanoderank=`grep -n -E "^${myhostname}$" ${KAFKA_CONF_DIR}/slaves | awk --field-separator=':' '{print $1}'`
+        fi
+        return 0
     fi
     return 1
 }
@@ -204,8 +204,8 @@ Magpie_am_I_a_zeppelin_node() {
 
     if grep -q -E "^${myhostname}$" ${ZEPPELIN_CONF_DIR}/masters
     then
-	zeppelinnoderank=`grep -n -E "^${myhostname}$" ${ZEPPELIN_CONF_DIR}/masters | awk --field-separator=':' '{print $1}'`
-	return 0
+        zeppelinnoderank=`grep -n -E "^${myhostname}$" ${ZEPPELIN_CONF_DIR}/masters | awk --field-separator=':' '{print $1}'`
+        return 0
     fi
     return 1
 }
@@ -216,15 +216,15 @@ Magpie_am_I_a_storm_node () {
     Magpie_make_storm_local_dirs_node_specific
 
     if grep -q -E "^${myhostname}$" ${STORM_CONF_DIR}/workers \
-	|| grep -q -E "^${myhostname}$" ${STORM_CONF_DIR}/masters
+        || grep -q -E "^${myhostname}$" ${STORM_CONF_DIR}/masters
     then 
-	if grep -q -E "^${myhostname}$" ${STORM_CONF_DIR}/masters
-	then
-	    stormnoderank=0
-	else
-	    stormnoderank=`grep -n -E "^${myhostname}$" ${STORM_CONF_DIR}/workers | awk --field-separator=':' '{print $1}'`
-	fi
-	return 0
+        if grep -q -E "^${myhostname}$" ${STORM_CONF_DIR}/masters
+        then
+            stormnoderank=0
+        else
+            stormnoderank=`grep -n -E "^${myhostname}$" ${STORM_CONF_DIR}/workers | awk --field-separator=':' '{print $1}'`
+        fi
+        return 0
     fi
     return 1
 }
@@ -235,15 +235,15 @@ Magpie_am_I_a_tachyon_node () {
     Magpie_make_tachyon_local_dirs_node_specific
 
     if grep -q -E "^${myhostname}$" ${TACHYON_CONF_DIR}/workers \
-	|| grep -q -E "^${myhostname}$" ${TACHYON_CONF_DIR}/masters
+        || grep -q -E "^${myhostname}$" ${TACHYON_CONF_DIR}/masters
     then 
-	if grep -q -E "^${myhostname}$" ${TACHYON_CONF_DIR}/masters
-	then
-	    tachyonnoderank=0
-	else
-	    tachyonnoderank=`grep -n -E "^${myhostname}$" ${TACHYON_CONF_DIR}/workers | awk --field-separator=':' '{print $1}'`
-	fi
-	return 0
+        if grep -q -E "^${myhostname}$" ${TACHYON_CONF_DIR}/masters
+        then
+            tachyonnoderank=0
+        else
+            tachyonnoderank=`grep -n -E "^${myhostname}$" ${TACHYON_CONF_DIR}/workers | awk --field-separator=':' '{print $1}'`
+        fi
+        return 0
     fi
     return 1
 }
@@ -254,14 +254,14 @@ Magpie_am_I_a_zookeeper_node () {
     Magpie_make_zookeeper_local_dirs_node_specific
 
     if grep -q -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_master \
-	|| grep -q -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves
+        || grep -q -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves
     then 
-	# The Zookeeper master is not a Zookeeper node, it gets no rank
-	if grep -q -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves
-	then
-	    zookeepernoderank=`grep -n -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves | awk --field-separator=':' '{print $1}'`
-	fi
-	return 0
+        # The Zookeeper master is not a Zookeeper node, it gets no rank
+        if grep -q -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves
+        then
+            zookeepernoderank=`grep -n -E "^${myhostname}$" ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves | awk --field-separator=':' '{print $1}'`
+        fi
+        return 0
     fi
     return 1
 }
@@ -271,91 +271,91 @@ Magpie_calculate_stop_timeouts () {
 
     if [ "${MAGPIE_POST_JOB_RUN}X" != "X" ]
     then
-	# Minimum 5 minutes or 1/3rd of time for MAGPIE_POST_JOB_RUN
-	local magpiepostrunallocate=`expr ${magpieshutdowntimeseconds} \/ 3`
-	if [ "${magpiepostrunallocate}" -lt 300 ]
-	then
-	    magpiepostrunallocate=300
-	fi
+        # Minimum 5 minutes or 1/3rd of time for MAGPIE_POST_JOB_RUN
+        local magpiepostrunallocate=`expr ${magpieshutdowntimeseconds} \/ 3`
+        if [ "${magpiepostrunallocate}" -lt 300 ]
+        then
+            magpiepostrunallocate=300
+        fi
 
-	magpieshutdowntimeseconds=`expr ${magpieshutdowntimeseconds} - ${magpiepostrunallocate}` 
+        magpieshutdowntimeseconds=`expr ${magpieshutdowntimeseconds} - ${magpiepostrunallocate}` 
     fi
 
     if [ "${HBASE_SETUP}" == "yes" ]
     then
-	# Need to give Hbase more time b/c of compaction.  We'll say
-	# Hbase always gets 50% of the time, Half for slave timeout and half for
-	# compaction .  Input checks ensure
-	# magpieshutdowntimeseconds >= 1200 
+        # Need to give Hbase more time b/c of compaction.  We'll say
+        # Hbase always gets 50% of the time, Half for slave timeout and half for
+        # compaction .  Input checks ensure
+        # magpieshutdowntimeseconds >= 1200 
 
-	local hbase_time=`expr ${magpieshutdowntimeseconds} \/ 2`
-	hbase_slave_timeout=`expr ${hbase_time} \/ 2`
-	magpieshutdowntimeseconds=${hbase_time}
+        local hbase_time=`expr ${magpieshutdowntimeseconds} \/ 2`
+        hbase_slave_timeout=`expr ${hbase_time} \/ 2`
+        magpieshutdowntimeseconds=${hbase_time}
     fi
 
     local stoptimeoutdivisor=1
 
     if [ "${HADOOP_SETUP}" == "yes" ]
     then
-	if [ ${HADOOP_SETUP_TYPE}  == "MR1" ] \
-	    || [ ${HADOOP_SETUP_TYPE}  == "MR2" ]
-	then
+        if [ ${HADOOP_SETUP_TYPE}  == "MR1" ] \
+            || [ ${HADOOP_SETUP_TYPE}  == "MR2" ]
+        then
             # Need to split timeout time between namenode, datanodes,
             # secondary namenode, jobtracker/resource manager,
             # tasktracker/nodemanagers, jobhistory server, & saveNameSpace
             # time
-	    stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 7`
-	else
+            stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 7`
+        else
             # Need to split timeout time between namenode, datanodes,
             # secondary namenode, jobhistory server, & saveNameSpace time
-	    stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 5`
-	fi    
+            stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 5`
+        fi    
     
-	# + 2 for scratch extra time in scripts and what not
-	stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
+        # + 2 for scratch extra time in scripts and what not
+        stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
     fi
 
     if [ "${SPARK_SETUP}" == "yes" ]
     then
-	# +2 for extra misc shutdown time
-	stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
+        # +2 for extra misc shutdown time
+        stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
     fi
 
     if [ "${STORM_SETUP}" == "yes" ]
     then
-	# +2 for extra misc shutdown time
-	stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
+        # +2 for extra misc shutdown time
+        stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
     fi
 
     if [ "${ZEPPELIN_SETUP}" == "yes" ]
     then
-	# +2 for extra misc shutdown time
-	stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
+        # +2 for extra misc shutdown time
+        stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
     fi
 
     if [ "${KAFKA_SETUP}" == "yes" ]
     then
-	# +2 for extra misc shutdown time
-	stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
+        # +2 for extra misc shutdown time
+        stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
     fi
 
     if [ "${PHOENIX_SETUP}" == "yes" ]
     then
-	# +2 for extra misc shutdown time
-	stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
+        # +2 for extra misc shutdown time
+        stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
     fi
 
     if [ "${ZOOKEEPER_SETUP}" == "yes" ]
     then
-	# +2 for extra misc shutdown time
-	stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
+        # +2 for extra misc shutdown time
+        stoptimeoutdivisor=`expr ${stoptimeoutdivisor} + 2`
     fi
 
     local stoptimeout=`expr ${magpieshutdowntimeseconds} \/ ${stoptimeoutdivisor}`
-	
+        
     if [ "${stoptimeout}" -lt 5 ]
     then
-	stoptimeout=5
+        stoptimeout=5
     fi
 
     hadoopstoptimeout=${stoptimeout}
@@ -368,28 +368,28 @@ Magpie_calculate_canrunjobscount () {
 
     if [ "${HADOOP_SETUP}" == "yes" ] && ( [ "${HADOOP_SETUP_TYPE}" == "MR1" ] || [ "${HADOOP_SETUP_TYPE}" == "MR2" ] )
     then
-	canrunjobscount=$((canrunjobscount+1))
+        canrunjobscount=$((canrunjobscount+1))
     fi
 
     if [ "${HBASE_SETUP}" == "yes" ]
     then
-	canrunjobscount=$((canrunjobscount+1))
+        canrunjobscount=$((canrunjobscount+1))
     fi
  
     if [ "${SPARK_SETUP}" == "yes" ] && [ "${SPARK_USE_YARN}" != "yes" ]
     then
-	canrunjobscount=$((canrunjobscount+1))
+        canrunjobscount=$((canrunjobscount+1))
     fi
 
     if [ "${STORM_SETUP}" == "yes" ]
     then
-	canrunjobscount=$((canrunjobscount+1))
+        canrunjobscount=$((canrunjobscount+1))
     fi
 
     # Could be zero in weird test scenarios
     if [ "${canrunjobscount}" == "0" ]
     then
-	canrunjobscount=1
+        canrunjobscount=1
     fi
 }
 
@@ -404,14 +404,14 @@ Magpie_calculate_threadstouse () {
 
     if [ "${canrunjobscount}" == "1" ]
     then
-	threadstouse=`expr ${proccount} + ${proccount} \/ 2`
+        threadstouse=`expr ${proccount} + ${proccount} \/ 2`
     else
-	threadstouse=`expr ${proccount} \/ ${canrunjobscount}`
+        threadstouse=`expr ${proccount} \/ ${canrunjobscount}`
 
-	if [ "${threadstouse}" == "0" ]
-	then
-	    threadstouse="1"
-	fi
+        if [ "${threadstouse}" == "0" ]
+        then
+            threadstouse="1"
+        fi
     fi
 }
 
@@ -439,21 +439,21 @@ Magpie_find_conffile () {
     
     if [ "${conffiledir}X" != "X" ]
     then
-	if [ -f "${conffiledir}/${conffiledesired}" ]
-	then
-	    conffilefound="${conffiledir}/${conffiledesired}"
-	fi
+        if [ -f "${conffiledir}/${conffiledesired}" ]
+        then
+            conffilefound="${conffiledir}/${conffiledesired}"
+        fi
     fi
 
     if [ "${conffilefound}X" == "X" ]
     then
-	conffilefound="${magpieconffiledir}/${conffiledesired}"
+        conffilefound="${magpieconffiledir}/${conffiledesired}"
     fi
 
     if [ ! -f ${conffilefound} ]
     then
-	echo "Missing ${project} configuration file ${conffiledesired}"
-	exit 1
+        echo "Missing ${project} configuration file ${conffiledesired}"
+        exit 1
     fi
 
     eval $__returnvar="${conffilefound}"
diff --git a/magpie-run-execute b/magpie-run-execute
--- a/magpie-run-execute
+++ b/magpie-run-execute
@@ -44,20 +44,20 @@ yarn_job_kill_handler () {
 
     for jobid in $prepjobs
     do
-	echo "Killing Yarn job id ${jobid}"
-	command="${HADOOP_HOME}/bin/mapred job -kill ${jobid}"
-	echo "Running $command" >&2
-	$command
+        echo "Killing Yarn job id ${jobid}"
+        command="${HADOOP_HOME}/bin/mapred job -kill ${jobid}"
+        echo "Running $command" >&2
+        $command
     done
 
     runningjobs=`${HADOOP_HOME}/bin/mapred job -list 2> /dev/null | grep RUNNING | awk '{print $1}'`
 
     for jobid in $runningjobs
     do
-	echo "Killing Yarn job id ${jobid}"
-	command="${HADOOP_HOME}/bin/mapred job -kill ${jobid}"
-	echo "Running $command" >&2
-	$command
+        echo "Killing Yarn job id ${jobid}"
+        command="${HADOOP_HOME}/bin/mapred job -kill ${jobid}"
+        echo "Running $command" >&2
+        $command
     done
 
     kill -s 9 ${childpid}
@@ -85,8 +85,8 @@ if [ "${jobtype}" == "script" ] || [ "${jobtype}" == "scriptnokill" ]
 then
     if [ "$2X" == "X" ]
     then
-	Magpie_output_internal_error "magpie-run-execute, second argument unset"
-	exit 1
+        Magpie_output_internal_error "magpie-run-execute, second argument unset"
+        exit 1
     fi
     scripttorun=$2
 fi
@@ -123,24 +123,24 @@ then
     echo "* to exit ${typemessage} early."
     if [ "${jobtype}" == "script" ]
     then
-	echo "*"
-	echo "* Warning: killing early may not kill jobs submitted to an internally"
-	echo "* managed scheduler within Magpie.  The job will be canceled during teardown"
-	echo "* of daemons.  Extraneous error messages from your job may occur until then."
+        echo "*"
+        echo "* Warning: killing early may not kill jobs submitted to an internally"
+        echo "* managed scheduler within Magpie.  The job will be canceled during teardown"
+        echo "* of daemons.  Extraneous error messages from your job may occur until then."
 
-	# We use SIGUSR1 and SIGUSR2 above & below.  Signal 28, SIGWINCH seems a good choice
-	# to use.
-	if [ "${HADOOP_SETUP}" == "yes" ] && [ "${HADOOP_SETUP_TYPE}" == "MR2" ]
-	then
-	    echo "*"
-	    echo "* Magpie is aware that Yarn has been launched.  If user wishes to"
-	    echo "* kill all currently submitted Yarn jobs in the PREP or" 
-	    echo "* RUNNING state to be killed before killing the job, run:"
-	    echo "*"
-	    echo "* ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} $(hostname) kill -s 28 ${mypid}"
+        # We use SIGUSR1 and SIGUSR2 above & below.  Signal 28, SIGWINCH seems a good choice
+        # to use.
+        if [ "${HADOOP_SETUP}" == "yes" ] && [ "${HADOOP_SETUP_TYPE}" == "MR2" ]
+        then
+            echo "*"
+            echo "* Magpie is aware that Yarn has been launched.  If user wishes to"
+            echo "* kill all currently submitted Yarn jobs in the PREP or" 
+            echo "* RUNNING state to be killed before killing the job, run:"
+            echo "*"
+            echo "* ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} $(hostname) kill -s 28 ${mypid}"
 
-	    trap "yarn_job_kill_handler ${childpid}" 28
-	fi
+            trap "yarn_job_kill_handler ${childpid}" 28
+        fi
     fi
     echo "*******************************************************"
 
diff --git a/magpie-run-job-hadoop-decommissionhdfsnodes b/magpie-run-job-hadoop-decommissionhdfsnodes
--- a/magpie-run-job-hadoop-decommissionhdfsnodes
+++ b/magpie-run-job-hadoop-decommissionhdfsnodes
@@ -46,14 +46,14 @@ if [ "${HADOOP_HDFS_REPLICATION}X" != "X" ]
 then
     if [ "${HADOOP_DECOMMISSION_HDFS_NODE_SIZE}" -lt "${HADOOP_HDFS_REPLICATION}" ]
     then
-	echo "Cannot have fewer nodes than HDFS replication"
-	exit 1
+        echo "Cannot have fewer nodes than HDFS replication"
+        exit 1
     fi
 else
     if [ "${HADOOP_DECOMMISSION_HDFS_NODE_SIZE}" -lt ${default_hdfs_replication} ]
     then
-	echo "Cannot have fewer nodes than HDFS replication"
-	exit 1
+        echo "Cannot have fewer nodes than HDFS replication"
+        exit 1
     fi
 fi
 
@@ -72,7 +72,7 @@ do
     count=`${hadoopcmdprefix}/hdfs dfsadmin -report | grep 'Decommission Status : Decommissioned' | wc -l`
     if [ ${count} -lt "${nodecounttodecommission}" ]
     then
-	echo "Done decommissioning ${count} nodes out of ${nodecounttodecommission} ... sleeping for a bit "
+        echo "Done decommissioning ${count} nodes out of ${nodecounttodecommission} ... sleeping for a bit "
         sleep 30
         continue
     fi
@@ -86,16 +86,16 @@ then
     count=0
     while [ "${count}" -lt "${nodecounttodecommission}" ]
     do
-	noderank=`expr ${HADOOP_SLAVE_COUNT} - ${count}`
+        noderank=`expr ${HADOOP_SLAVE_COUNT} - ${count}`
         if [ "${HADOOP_PER_JOB_HDFS_PATH}" == "yes" ]
         then
-  	    rmpath="${HADOOP_HDFSOVERLUSTRE_PATH}/${MAGPIE_JOB_ID}/node-$noderank"
+            rmpath="${HADOOP_HDFSOVERLUSTRE_PATH}/${MAGPIE_JOB_ID}/node-$noderank"
         else
-  	    rmpath="${HADOOP_HDFSOVERLUSTRE_PATH}/node-$noderank"
+            rmpath="${HADOOP_HDFSOVERLUSTRE_PATH}/node-$noderank"
         fi    
-	echo "Removing path ${rmpath} ..."
-	rm -rf ${rmpath}
-	count=`expr $count + 1`
+        echo "Removing path ${rmpath} ..."
+        rm -rf ${rmpath}
+        count=`expr $count + 1`
     done
 fi
 
@@ -104,16 +104,16 @@ then
     count=0
     while [ "${count}" -lt "${nodecounttodecommission}" ]
     do
-	noderank=`expr ${HADOOP_SLAVE_COUNT} - ${count}`
+        noderank=`expr ${HADOOP_SLAVE_COUNT} - ${count}`
         if [ "${HADOOP_PER_JOB_HDFS_PATH}" == "yes" ]
         then
-	    rmpath="${HADOOP_HDFSOVERNETWORKFS_PATH}/${MAGPIE_JOB_ID}/node-$noderank"
+            rmpath="${HADOOP_HDFSOVERNETWORKFS_PATH}/${MAGPIE_JOB_ID}/node-$noderank"
         else
-	    rmpath="${HADOOP_HDFSOVERNETWORKFS_PATH}/node-$noderank"
+            rmpath="${HADOOP_HDFSOVERNETWORKFS_PATH}/node-$noderank"
         fi
-	echo "Removing path ${rmpath} ..."
-	rm -rf ${rmpath}
-	count=`expr $count + 1`
+        echo "Removing path ${rmpath} ..."
+        rm -rf ${rmpath}
+        count=`expr $count + 1`
     done
 fi
 
diff --git a/magpie-run-project-tachyon b/magpie-run-project-tachyon
--- a/magpie-run-project-tachyon
+++ b/magpie-run-project-tachyon
@@ -38,231 +38,231 @@ source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-misc-external
 Magpie_run_start_tachyon () {
     if [ "${TACHYON_SETUP}" == "yes" ] && [ "${prior_setup_successful}" == "true" ]
     then
-	if [ "${hadoop_setup_successful}" == "0" ]
-	then
-	    Magpie_output_internal_error "Attempt to setup Tachyon without Hadoop being setup"
-	    tachyon_should_be_torndown=0
-	    tachyon_setup_successful=0
-	    return 1
-	fi
+        if [ "${hadoop_setup_successful}" == "0" ]
+        then
+            Magpie_output_internal_error "Attempt to setup Tachyon without Hadoop being setup"
+            tachyon_should_be_torndown=0
+            tachyon_setup_successful=0
+            return 1
+        fi
 
-	cd ${TACHYON_HOME}
+        cd ${TACHYON_HOME}
 
-	if [ ${TACHYON_MODE} != "setuponly" ]
-	then
-	    # Must be done here instead of in magpie-setup-tachyon, b/c
-	    # if Hadoop is setup, the format needs to contact HDFS
-	    if [ "${TACHYON_JOURNAL_FOLDER}X" == "X" ]
-	    then
-		local tachyonformat=1
-	    else
-		if [ ! -d "${TACHYON_JOURNAL_FOLDER}" ]
-		then
-		    local tachyonformat=1
+        if [ ${TACHYON_MODE} != "setuponly" ]
+        then
+            # Must be done here instead of in magpie-setup-tachyon, b/c
+            # if Hadoop is setup, the format needs to contact HDFS
+            if [ "${TACHYON_JOURNAL_FOLDER}X" == "X" ]
+            then
+                local tachyonformat=1
+            else
+                if [ ! -d "${TACHYON_JOURNAL_FOLDER}" ]
+                then
+                    local tachyonformat=1
 
-		    mkdir -p ${TACHYON_JOURNAL_FOLDER}
-		    if [ $? -ne 0 ] ; then
-			echo "mkdir failed making ${TACHYON_JOURNAL_FOLDER}"
-			exit 1
-		    fi
-		else
-		    local tachyonformat=0
-		fi
-	    fi
+                    mkdir -p ${TACHYON_JOURNAL_FOLDER}
+                    if [ $? -ne 0 ] ; then
+                        echo "mkdir failed making ${TACHYON_JOURNAL_FOLDER}"
+                        exit 1
+                    fi
+                else
+                    local tachyonformat=0
+                fi
+            fi
 
-	    if [ "${tachyonformat}" == "1" ]
-	    then
-		echo "*******************************************************"
-		echo "* Formatting Tachyon"
-		echo "*******************************************************"
-		${tachyoncmdprefix}/tachyon format
+            if [ "${tachyonformat}" == "1" ]
+            then
+                echo "*******************************************************"
+                echo "* Formatting Tachyon"
+                echo "*******************************************************"
+                ${tachyoncmdprefix}/tachyon format
 
                 # My rough estimate for setup time is 15 seconds per 128 nodes
-		local sleepwait=`expr ${TACHYON_SLAVE_COUNT} \/ 128 \* 15`
-		if [ ${sleepwait} -lt 15 ]
-		then
-		    sleepwait=15
-		fi
-		echo "Waiting ${sleepwait} seconds to allow Tachyon format to complete"
-		sleep ${sleepwait}
-		totalsleepwait=`expr ${totalsleepwait} + ${sleepwait}`
-	    fi
+                local sleepwait=`expr ${TACHYON_SLAVE_COUNT} \/ 128 \* 15`
+                if [ ${sleepwait} -lt 15 ]
+                then
+                    sleepwait=15
+                fi
+                echo "Waiting ${sleepwait} seconds to allow Tachyon format to complete"
+                sleep ${sleepwait}
+                totalsleepwait=`expr ${totalsleepwait} + ${sleepwait}`
+            fi
 
-	    echo "Starting tachyon"
-	    ${tachyoncmdprefix}/tachyon-start.sh -N all NoMount
-	    
+            echo "Starting tachyon"
+            ${tachyoncmdprefix}/tachyon-start.sh -N all NoMount
+            
             # My rough estimate for setup time is 30 seconds per 128 nodes
-	    local sleepwait=`expr ${TACHYON_SLAVE_COUNT} \/ 128 \* 30`
-	    if [ ${sleepwait} -lt 30 ]
-	    then
-		sleepwait=30
-	    fi
-	    echo "Waiting ${sleepwait} seconds to allow Tachyon daemons to setup"
-	    sleep ${sleepwait}
-	    totalsleepwait=`expr ${totalsleepwait} + ${sleepwait}`
-	fi
+            local sleepwait=`expr ${TACHYON_SLAVE_COUNT} \/ 128 \* 30`
+            if [ ${sleepwait} -lt 30 ]
+            then
+                sleepwait=30
+            fi
+            echo "Waiting ${sleepwait} seconds to allow Tachyon daemons to setup"
+            sleep ${sleepwait}
+            totalsleepwait=`expr ${totalsleepwait} + ${sleepwait}`
+        fi
 
-	echo "*******************************************************"
-	echo "*"
-	echo "* Tachyon Information"
-	echo "*"
-	echo "* You can view your Tachyon status by launching a web browser and pointing to ..."
-	echo "*"
-	echo "* Tachyon UI: http://${TACHYON_MASTER_NODE}:${TACHYON_MASTER_WEB_PORT}"
-	echo "*" 
-	echo "* To access Tachyon directly, you'll most likely want to:"
-	echo "*   ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} <WORKERNODE>"
-	if echo $MAGPIE_SHELL | grep -q csh
-	then
-	    echo "*   setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\""
-	else
-	    echo "*   export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\""
-	fi
-	echo "*   cd $TACHYON_HOME"
-	echo "*"
-	echo "* Then you can do as you please.  For example:"
-	echo "*" 
-	echo "*   ${tachyoncmdprefix}/tachyon tfs ls /"
-	echo "*" 
+        echo "*******************************************************"
+        echo "*"
+        echo "* Tachyon Information"
+        echo "*"
+        echo "* You can view your Tachyon status by launching a web browser and pointing to ..."
+        echo "*"
+        echo "* Tachyon UI: http://${TACHYON_MASTER_NODE}:${TACHYON_MASTER_WEB_PORT}"
+        echo "*" 
+        echo "* To access Tachyon directly, you'll most likely want to:"
+        echo "*   ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} <WORKERNODE>"
+        if echo $MAGPIE_SHELL | grep -q csh
+        then
+            echo "*   setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\""
+        else
+            echo "*   export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\""
+        fi
+        echo "*   cd $TACHYON_HOME"
+        echo "*"
+        echo "* Then you can do as you please.  For example:"
+        echo "*" 
+        echo "*   ${tachyoncmdprefix}/tachyon tfs ls /"
+        echo "*" 
 
-	if [ "${TACHYON_MODE}" == "setuponly" ]
-	then
- 	    echo "* To setup, you probably want to run:" 
-	    echo "*"
-	    echo "*   ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} ${TACHYON_MASTER_NODE}"
-	    if echo $MAGPIE_SHELL | grep -q csh
-	    then
-		echo "*   setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\""
-	    else
-		echo "*   export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\""
-	    fi
-	    echo "*   cd $TACHYON_HOME"
-	    echo "*   ${tachyoncmdprefix}/tachyon format"
-	    echo "*   ${tachyoncmdprefix}/tachyon-start.sh -N all NoMount"
-	    echo "*" 
-	fi
+        if [ "${TACHYON_MODE}" == "setuponly" ]
+        then
+            echo "* To setup, you probably want to run:" 
+            echo "*"
+            echo "*   ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} ${TACHYON_MASTER_NODE}"
+            if echo $MAGPIE_SHELL | grep -q csh
+            then
+                echo "*   setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\""
+            else
+                echo "*   export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\""
+            fi
+            echo "*   cd $TACHYON_HOME"
+            echo "*   ${tachyoncmdprefix}/tachyon format"
+            echo "*   ${tachyoncmdprefix}/tachyon-start.sh -N all NoMount"
+            echo "*" 
+        fi
 
-	echo "* To end/cleanup your session, kill the daemons via:"
-	echo "*" 
-	echo "*   ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} ${TACHYON_MASTER_NODE}"
-	if echo $MAGPIE_SHELL | grep -q csh
-	then
-	    echo "*   setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\""
-	else
-	    echo "*   export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\""
-	fi
-	echo "*   cd $TACHYON_HOME"
-	echo "*   ${tachyoncmdprefix}/tachyon-stop.sh all"
-	echo "*" 
-	echo "* Some additional environment variables you may sometimes wish to set"
-	echo "*" 
-	if echo $MAGPIE_SHELL | grep -q csh
-	then
-	    echo "*   setenv JAVA_HOME \"${JAVA_HOME}\""
-	    echo "*   setenv TACHYON_HOME \"${TACHYON_HOME}\""
-	else
-	    echo "*   export JAVA_HOME=\"${JAVA_HOME}\""
-	    echo "*   export TACHYON_HOME=\"${TACHYON_HOME}\""
-	fi
+        echo "* To end/cleanup your session, kill the daemons via:"
+        echo "*" 
+        echo "*   ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} ${TACHYON_MASTER_NODE}"
+        if echo $MAGPIE_SHELL | grep -q csh
+        then
+            echo "*   setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\""
+        else
+            echo "*   export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\""
+        fi
+        echo "*   cd $TACHYON_HOME"
+        echo "*   ${tachyoncmdprefix}/tachyon-stop.sh all"
+        echo "*" 
+        echo "* Some additional environment variables you may sometimes wish to set"
+        echo "*" 
+        if echo $MAGPIE_SHELL | grep -q csh
+        then
+            echo "*   setenv JAVA_HOME \"${JAVA_HOME}\""
+            echo "*   setenv TACHYON_HOME \"${TACHYON_HOME}\""
+        else
+            echo "*   export JAVA_HOME=\"${JAVA_HOME}\""
+            echo "*   export TACHYON_HOME=\"${TACHYON_HOME}\""
+        fi
 
-	if [ "${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}X" != "X" ]
-	then
-	    echo "*"
-	    echo "* If running interactively, sourcing"
-	    echo "*"
-	    echo "* ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}"
-	    echo "*"
-	    echo "* will set most common environment variables for your job."
-	fi
-	echo "*" 
-	echo "*******************************************************"
+        if [ "${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}X" != "X" ]
+        then
+            echo "*"
+            echo "* If running interactively, sourcing"
+            echo "*"
+            echo "* ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}"
+            echo "*"
+            echo "* will set most common environment variables for your job."
+        fi
+        echo "*" 
+        echo "*******************************************************"
 
-	if [ "${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}X" != "X" ]
-	then
-	    if echo $MAGPIE_SHELL | grep -q csh
-	    then
-		echo "setenv TACHYON_HOME \"${TACHYON_HOME}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "setenv TACHYON_LOG_DIR \"${TACHYON_LOG_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "setenv TACHYON_MASTER_NODE \"${TACHYON_MASTER_NODE}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "setenv TACHYON_MASTER_PORT \"${TACHYON_MASTER_PORT}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "setenv TACHYON_FIRST_WORKER_NODE \"${TACHYON_FIRST_WORKER_NODE}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "setenv TACHYON_SLAVE_COUNT \"${TACHYON_SLAVE_COUNT}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "setenv TACHYON_VERSION \"${TACHYON_VERSION}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-	    else
-		echo "export TACHYON_HOME=\"${TACHYON_HOME}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "export TACHYON_LOG_DIR=\"${TACHYON_LOG_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "export TACHYON_MASTER_NODE=\"${TACHYON_MASTER_NODE}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "export TACHYON_MASTER_PORT=\"${TACHYON_MASTER_PORT}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "export TACHYON_FIRST_WORKER_NODE=\"${TACHYON_FIRST_WORKER_NODE}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "export TACHYON_SLAVE_COUNT=\"${TACHYON_SLAVE_COUNT}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-		echo "export TACHYON_VERSION=\"${TACHYON_VERSION}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-	    fi
-	    echo "" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
-	fi
+        if [ "${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}X" != "X" ]
+        then
+            if echo $MAGPIE_SHELL | grep -q csh
+            then
+                echo "setenv TACHYON_HOME \"${TACHYON_HOME}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "setenv TACHYON_CONF_DIR \"${TACHYON_CONF_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "setenv TACHYON_LOG_DIR \"${TACHYON_LOG_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "setenv TACHYON_MASTER_NODE \"${TACHYON_MASTER_NODE}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "setenv TACHYON_MASTER_PORT \"${TACHYON_MASTER_PORT}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "setenv TACHYON_FIRST_WORKER_NODE \"${TACHYON_FIRST_WORKER_NODE}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "setenv TACHYON_SLAVE_COUNT \"${TACHYON_SLAVE_COUNT}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "setenv TACHYON_VERSION \"${TACHYON_VERSION}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+            else
+                echo "export TACHYON_HOME=\"${TACHYON_HOME}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "export TACHYON_CONF_DIR=\"${TACHYON_CONF_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "export TACHYON_LOG_DIR=\"${TACHYON_LOG_DIR}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "export TACHYON_MASTER_NODE=\"${TACHYON_MASTER_NODE}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "export TACHYON_MASTER_PORT=\"${TACHYON_MASTER_PORT}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "export TACHYON_FIRST_WORKER_NODE=\"${TACHYON_FIRST_WORKER_NODE}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "export TACHYON_SLAVE_COUNT=\"${TACHYON_SLAVE_COUNT}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+                echo "export TACHYON_VERSION=\"${TACHYON_VERSION}\"" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+            fi
+            echo "" >> ${MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT}
+        fi
 
         # Nothing to check for Tachyon, setup always passes
-	tachyon_should_be_torndown=1
-	tachyon_setup_successful=1
+        tachyon_should_be_torndown=1
+        tachyon_setup_successful=1
     else
-	tachyon_should_be_torndown=0
-	tachyon_setup_successful=1
+        tachyon_should_be_torndown=0
+        tachyon_setup_successful=1
     fi
 }
 
 Magpie_run_tachyon () {
     if [ "${TACHYON_MODE}" == "testtachyon" ]
     then
-	echo "*******************************************************"
-	echo "* Running Testtachyon"
-	echo "*******************************************************"
-	${MAGPIE_SCRIPTS_HOME}/magpie-run-execute script ${MAGPIE_SCRIPTS_HOME}/magpie-run-job-tachyon-testtachyon &
-	local scriptpid=$!
-	Magpie_wait_script_sigusr2_on_job_timeout ${scriptpid}
+        echo "*******************************************************"
+        echo "* Running Testtachyon"
+        echo "*******************************************************"
+        ${MAGPIE_SCRIPTS_HOME}/magpie-run-execute script ${MAGPIE_SCRIPTS_HOME}/magpie-run-job-tachyon-testtachyon &
+        local scriptpid=$!
+        Magpie_wait_script_sigusr2_on_job_timeout ${scriptpid}
     elif [ "${TACHYON_MODE}" == "launch" ]
     then
-	echo "*******************************************************"
-	echo "* Entering Tachyon ${TACHYON_MODE} mode"
-	echo "*******************************************************"
-	${MAGPIE_SCRIPTS_HOME}/magpie-run-execute launch &
-	local scriptpid=$!
+        echo "*******************************************************"
+        echo "* Entering Tachyon ${TACHYON_MODE} mode"
+        echo "*******************************************************"
+        ${MAGPIE_SCRIPTS_HOME}/magpie-run-execute launch &
+        local scriptpid=$!
         wait $scriptpid
     elif [ "${TACHYON_MODE}" == "setuponly" ]
     then
-	echo "*******************************************************"
-	echo "* Entering Tachyon ${TACHYON_MODE} mode"
-	echo "*******************************************************"
-	${MAGPIE_SCRIPTS_HOME}/magpie-run-job-sleep countdown &
-	local scriptpid=$!
-	wait ${scriptpid}
+        echo "*******************************************************"
+        echo "* Entering Tachyon ${TACHYON_MODE} mode"
+        echo "*******************************************************"
+        ${MAGPIE_SCRIPTS_HOME}/magpie-run-job-sleep countdown &
+        local scriptpid=$!
+        wait ${scriptpid}
     fi
 }
 
 Magpie_run_stop_tachyon () {
     if [ "${hadoop_teardown_complete}" == "1" ]
     then
-	Magpie_output_internal_warning "tearing down Tachyon after Hadoop"
+        Magpie_output_internal_warning "tearing down Tachyon after Hadoop"
     fi
 
     if [ "${TACHYON_SETUP}" == "yes" ] && [ "${tachyon_should_be_torndown}" == "1" ]
     then
-	if [ ${TACHYON_MODE} != "setuponly" ]
-	then
-	    cd ${TACHYON_HOME}
-	    
-	    if [ "${TACHYON_JOURNAL_FOLDER}X" == "X" ]
-	    then
-		echo "Clearing tachyon data"
-		
-		command="${tachyoncmdprefix}/tachyon tfs rmr /"
-		echo "Running $command" >&2
-		$command
-	    fi
-	    
-	    echo "Stopping tachyon"
-	${tachyoncmdprefix}/tachyon-stop.sh all
-	fi
+        if [ ${TACHYON_MODE} != "setuponly" ]
+        then
+            cd ${TACHYON_HOME}
+            
+            if [ "${TACHYON_JOURNAL_FOLDER}X" == "X" ]
+            then
+                echo "Clearing tachyon data"
+                
+                command="${tachyoncmdprefix}/tachyon tfs rmr /"
+                echo "Running $command" >&2
+                $command
+            fi
+            
+            echo "Stopping tachyon"
+        ${tachyoncmdprefix}/tachyon-stop.sh all
+        fi
     fi
     tachyon_teardown_complete=1
 }
diff --git a/magpie-setup-core b/magpie-setup-core
--- a/magpie-setup-core
+++ b/magpie-setup-core
@@ -65,32 +65,32 @@ do
 
     if [ "${!setupvar}" == "yes" ]
     then
-	if [ "${!confdirvar}X" != "X" ]
-	then
-	    mkdir -p ${!confdirvar}
-	    if [ $? -ne 0 ] ; then
-		echo "mkdir failed making ${!confdirvar}"
-		exit 1
-	    fi
-	fi
+        if [ "${!confdirvar}X" != "X" ]
+        then
+            mkdir -p ${!confdirvar}
+            if [ $? -ne 0 ] ; then
+                echo "mkdir failed making ${!confdirvar}"
+                exit 1
+            fi
+        fi
 
-	if [ "${!logdirvar}X" != "X" ]
-	then
-	    mkdir -p ${!logdirvar}
-	    if [ $? -ne 0 ] ; then
-		echo "mkdir failed making ${!logdirvar}"
-		exit 1
-	    fi
-	fi
+        if [ "${!logdirvar}X" != "X" ]
+        then
+            mkdir -p ${!logdirvar}
+            if [ $? -ne 0 ] ; then
+                echo "mkdir failed making ${!logdirvar}"
+                exit 1
+            fi
+        fi
 
-	if [ "${!localscratchspacedirvar}X" != "X" ]
-	then
-	    mkdir -p ${!localscratchspacedirvar}
-	    if [ $? -ne 0 ] ; then
-		echo "mkdir failed making ${!localscratchspacedirvar}"
-		exit 1
-	    fi
-	fi
+        if [ "${!localscratchspacedirvar}X" != "X" ]
+        then
+            mkdir -p ${!localscratchspacedirvar}
+            if [ $? -ne 0 ] ; then
+                echo "mkdir failed making ${!localscratchspacedirvar}"
+                exit 1
+            fi
+        fi
     fi
 done
 
@@ -106,11 +106,11 @@ then
 else
     if [ -x ${MAGPIE_SCRIPTS_HOME}/bin/magpie-expand-nodes ]
     then
-	hostrangescript="${MAGPIE_SCRIPTS_HOME}/bin/magpie-expand-nodes"
-	hostrangescriptoptions=""
+        hostrangescript="${MAGPIE_SCRIPTS_HOME}/bin/magpie-expand-nodes"
+        hostrangescriptoptions=""
     else
-	echo "Cannot find tool to expand host ranges"
-	exit 1
+        echo "Cannot find tool to expand host ranges"
+        exit 1
     fi
 fi
 
@@ -142,9 +142,9 @@ then
 
     if [ "${ZOOKEEPER_SHARE_NODES}" != "yes" ] 
     then
-	head -${jobslavecount} ${MAGPIE_LOCAL_CONF_DIR}/tmp_slaves > ${MAGPIE_LOCAL_CONF_DIR}/job_slaves
+        head -${jobslavecount} ${MAGPIE_LOCAL_CONF_DIR}/tmp_slaves > ${MAGPIE_LOCAL_CONF_DIR}/job_slaves
     else
-	cp ${MAGPIE_LOCAL_CONF_DIR}/tmp_slaves ${MAGPIE_LOCAL_CONF_DIR}/job_slaves
+        cp ${MAGPIE_LOCAL_CONF_DIR}/tmp_slaves ${MAGPIE_LOCAL_CONF_DIR}/job_slaves
     fi
 
     tail -n+${zookeeperslavestart} ${MAGPIE_LOCAL_CONF_DIR}/tmp_slaves > ${ZOOKEEPER_CONF_DIR}/zookeeper_slaves 
@@ -162,7 +162,7 @@ then
     cp ${MAGPIE_LOCAL_CONF_DIR}/job_slaves ${HADOOP_CONF_DIR}/slaves
     if [ -f "${MAGPIE_LOCAL_CONF_DIR}/namenode_hdfs_federation" ]
     then
-	cp ${MAGPIE_LOCAL_CONF_DIR}/namenode_hdfs_federation ${HADOOP_CONF_DIR}/namenode_hdfs_federation
+        cp ${MAGPIE_LOCAL_CONF_DIR}/namenode_hdfs_federation ${HADOOP_CONF_DIR}/namenode_hdfs_federation
     fi
 
     slavenodes=`cat ${HADOOP_CONF_DIR}/slaves`
@@ -172,7 +172,7 @@ then
     # We assume FQDN across all nodes is the same
     for node in ${slavenodes}
     do
-	echo "${node}.${dnsdomainname}" >> ${HADOOP_CONF_DIR}/slaves_fqdn
+        echo "${node}.${dnsdomainname}" >> ${HADOOP_CONF_DIR}/slaves_fqdn
     done
 fi
 
@@ -219,10 +219,10 @@ then
     cp ${MAGPIE_LOCAL_CONF_DIR}/job_masters ${TACHYON_CONF_DIR}/masters
     if [ "${TACHYON_WORKER_ON_MASTER}" == "yes" ]
     then
-	cp ${MAGPIE_LOCAL_CONF_DIR}/job_masters ${TACHYON_CONF_DIR}/workers
-	cat ${MAGPIE_LOCAL_CONF_DIR}/job_slaves >> ${TACHYON_CONF_DIR}/workers
+        cp ${MAGPIE_LOCAL_CONF_DIR}/job_masters ${TACHYON_CONF_DIR}/workers
+        cat ${MAGPIE_LOCAL_CONF_DIR}/job_slaves >> ${TACHYON_CONF_DIR}/workers
     else
-	cp ${MAGPIE_LOCAL_CONF_DIR}/job_slaves ${TACHYON_CONF_DIR}/workers
+        cp ${MAGPIE_LOCAL_CONF_DIR}/job_slaves ${TACHYON_CONF_DIR}/workers
     fi
 fi
 
diff --git a/magpie-setup-hbase b/magpie-setup-hbase
--- a/magpie-setup-hbase
+++ b/magpie-setup-hbase
@@ -69,7 +69,7 @@ else
 
     if [ "${hbaseresourcememory}" -lt "${hbaseregionserverdaemonheapmax}" ]
     then
-	hbaseregionserverdaemonheapmax=${hbaseresourcememory}
+        hbaseregionserverdaemonheapmax=${hbaseresourcememory}
     fi
 fi
 
@@ -110,8 +110,8 @@ if [ ! -d "${hbasetmpdir}" ]
 then
     mkdir -p ${hbasetmpdir}
     if [ $? -ne 0 ] ; then
-	echo "mkdir failed making ${hbasetmpdir}"
-	exit 1
+        echo "mkdir failed making ${hbasetmpdir}"
+        exit 1
     fi
 fi
 
@@ -138,11 +138,11 @@ then
     openfilescount=`expr ${openfilesslavecount} \* 16384`
     if [ "${openfilescount}" -lt "32768" ]
     then
-	openfilescount=32768
+        openfilescount=32768
     fi
     if [ "${openfilescount}" -gt "131072" ]
     then
-	openfilescount=131072
+        openfilescount=131072
     fi
     
     if [ "${openfileshardlimit}" != "unlimited" ]
@@ -166,11 +166,11 @@ then
     userprocessescount=`expr ${userprocessesslavecount} \* 2048`
     if [ "${userprocessescount}" -lt "4096" ]
     then
-	userprocessescount=4096
+        userprocessescount=4096
     fi
     if [ "${userprocessescount}" -gt "32768" ]
     then
-	userprocessescount=32768
+        userprocessescount=32768
     fi
     
     if [ "${userprocesseshardlimit}" != "unlimited" ]
@@ -191,8 +191,8 @@ if [ ! -d "${HBASE_LOCAL_SCRATCHSPACE_DIR}/tmp" ]
 then
     mkdir -p ${HBASE_LOCAL_SCRATCHSPACE_DIR}/tmp
     if [ $? -ne 0 ] ; then
-	echo "mkdir failed making ${HBASE_LOCAL_SCRATCHSPACE_DIR}/tmp"
-	exit 1
+        echo "mkdir failed making ${HBASE_LOCAL_SCRATCHSPACE_DIR}/tmp"
+        exit 1
     fi
 fi
 
diff --git a/magpie-setup-spark b/magpie-setup-spark
--- a/magpie-setup-spark
+++ b/magpie-setup-spark
@@ -132,11 +132,11 @@ then
     
     if [ ! -d "${sparklocalscratchdirpath}" ]
     then
-	mkdir -p ${sparklocalscratchdirpath}
-	if [ $? -ne 0 ] ; then
-	    echo "mkdir failed making ${sparklocalscratchdirpath}"
-	    exit 1
-	fi
+        mkdir -p ${sparklocalscratchdirpath}
+        if [ $? -ne 0 ] ; then
+            echo "mkdir failed making ${sparklocalscratchdirpath}"
+            exit 1
+        fi
     fi
 else
     IFSORIG=${IFS}
@@ -145,18 +145,18 @@ else
     for sparklocalpath in ${SPARK_LOCAL_SCRATCH_DIR}
     do
         # Setup node directory per node in case not a local drive
-	sparklocalpathtmp="${sparklocalpath}/node-${sparknoderank}"
+        sparklocalpathtmp="${sparklocalpath}/node-${sparknoderank}"
 
-	if [ ! -d "${sparklocalpathtmp}" ]
-	then
-	    mkdir -p ${sparklocalpathtmp}
-	    if [ $? -ne 0 ] ; then
-		echo "mkdir failed making ${sparklocalpathtmp}"
-		exit 1
-	    fi
-	fi
+        if [ ! -d "${sparklocalpathtmp}" ]
+        then
+            mkdir -p ${sparklocalpathtmp}
+            if [ $? -ne 0 ] ; then
+                echo "mkdir failed making ${sparklocalpathtmp}"
+                exit 1
+            fi
+        fi
 
-	sparklocalscratchdirpath="${sparklocalscratchdirpath}${sparklocalscratchdirpath:+","}${sparklocalpathtmp}"
+        sparklocalscratchdirpath="${sparklocalscratchdirpath}${sparklocalscratchdirpath:+","}${sparklocalpathtmp}"
     done
     IFS=${IFSORIG}
 fi
@@ -173,31 +173,31 @@ if [ "${HADOOP_SETUP}" == "yes" ]
 then
     if [ "${HADOOP_FILESYSTEM_MODE}" == "hdfs" ]
     then
-	sparkshufflebufferkb=100
-	sparkshufflebuffer=100k
-	sparkshuffleconsolidatefiles="false"
+        sparkshufflebufferkb=100
+        sparkshufflebuffer=100k
+        sparkshuffleconsolidatefiles="false"
     elif [ "${HADOOP_FILESYSTEM_MODE}" == "hdfsoverlustre" ] \
-	|| [ "${HADOOP_FILESYSTEM_MODE}" == "hdfsovernetworkfs" ]
+        || [ "${HADOOP_FILESYSTEM_MODE}" == "hdfsovernetworkfs" ]
     then
         # Default block size is 1M in Lustre
         # XXX: If not default, can get from lctl or similar?
         # If other networkFS, just assume like Lustre
-	sparkshufflebufferkb=1024
-	sparkshufflebuffer=1024k
-	sparkshuffleconsolidatefiles="true"
+        sparkshufflebufferkb=1024
+        sparkshufflebuffer=1024k
+        sparkshuffleconsolidatefiles="true"
     elif [ "${HADOOP_FILESYSTEM_MODE}" == "rawnetworkfs" ] \
-	|| [ "${HADOOP_FILESYSTEM_MODE}" == "magpienetworkfs" ]
+        || [ "${HADOOP_FILESYSTEM_MODE}" == "magpienetworkfs" ]
     then
         # Assuming Lustre, so copy above 1M
-	sparkshufflebufferkb=1024
-	sparkshufflebuffer=1024k
-	sparkshuffleconsolidatefiles="true"
+        sparkshufflebufferkb=1024
+        sparkshufflebuffer=1024k
+        sparkshuffleconsolidatefiles="true"
     elif [ "${HADOOP_FILESYSTEM_MODE}" == "intellustre" ]
     then
         # Assuming Lustre, so copy above 1M
-	sparkshufflebufferkb=1024
-	sparkshufflebuffer=1024k
-	sparkshuffleconsolidatefiles="true"
+        sparkshufflebufferkb=1024
+        sparkshufflebuffer=1024k
+        sparkshuffleconsolidatefiles="true"
     fi 
 else
     # Accessing filesystem directly, assume Lustre
@@ -312,11 +312,11 @@ then
     openfilescount=`expr ${openfilesslavecount} \* 8192`
     if [ "${openfilescount}" -lt "16384" ]
     then
-	openfilescount=16384
+        openfilescount=16384
     fi
     if [ "${openfilescount}" -gt "65536" ]
     then
-	openfilescount=65536
+        openfilescount=65536
     fi
     
     if [ "${openfileshardlimit}" != "unlimited" ]
@@ -340,11 +340,11 @@ then
     userprocessescount=`expr ${userprocessesslavecount} \* 2048`
     if [ "${userprocessescount}" -lt "4096" ]
     then
-	userprocessescount=4096
+        userprocessescount=4096
     fi
     if [ "${userprocessescount}" -gt "32768" ]
     then
-	userprocessescount=32768
+        userprocessescount=32768
     fi
     
     if [ "${userprocesseshardlimit}" != "unlimited" ]
@@ -362,9 +362,9 @@ if [ "${SPARK_JOB_JAVA_OPTS}X" != "X" ]
 then
     if [ "${SPARK_JAVA_OPTS}X" != "X" ]
     then
-	SPARK_JAVA_OPTS="${SPARK_JAVA_OPTS} ${SPARK_JOB_JAVA_OPTS}"
+        SPARK_JAVA_OPTS="${SPARK_JAVA_OPTS} ${SPARK_JOB_JAVA_OPTS}"
     else
-	SPARK_JAVA_OPTS="${SPARK_JOB_JAVA_OPTS}"
+        SPARK_JAVA_OPTS="${SPARK_JOB_JAVA_OPTS}"
     fi
 fi
 
@@ -379,7 +379,7 @@ if [ "${SPARK_JAVA_OPTS}X" != "X" ]
 then
     if ! echo ${SPARK_JAVA_OPTS} | grep -q -E "java.io.tmpdir"
     then
-	export SPARK_JAVA_OPTS="${SPARK_JAVA_OPTS} -Djava.io.tmpdir=${SPARK_LOCAL_SCRATCHSPACE_DIR}/tmp"
+        export SPARK_JAVA_OPTS="${SPARK_JAVA_OPTS} -Djava.io.tmpdir=${SPARK_LOCAL_SCRATCHSPACE_DIR}/tmp"
     fi
 fi
 
@@ -475,10 +475,10 @@ sed -i \
 if [ "${SPARK_USE_YARN}" == "yes" ]
 then
     sed -i \
-	-e "s/export SPARK_MASTER_PORT/# export SPARK_MASTER_PORT/g" \
-	-e "s/export SPARK_MASTER_WEBUI_PORT/# export SPARK_MASTER_WEBUI_PORT/g" \
-	-e "s/export SPARK_WORKER_WEBUI_PORT/# export SPARK_WORKER_WEBUI_PORT/g" \
-	${post_sparkenvsh}
+        -e "s/export SPARK_MASTER_PORT/# export SPARK_MASTER_PORT/g" \
+        -e "s/export SPARK_MASTER_WEBUI_PORT/# export SPARK_MASTER_WEBUI_PORT/g" \
+        -e "s/export SPARK_WORKER_WEBUI_PORT/# export SPARK_WORKER_WEBUI_PORT/g" \
+        ${post_sparkenvsh}
 fi
 
 echo "export SPARK_LOG_DIR=\"${SPARK_LOG_DIR}\"" >> ${post_sparkenvsh}
@@ -495,9 +495,9 @@ then
     
     if [ "${sparkclasspath}X" != "X" ]
     then
-	sparkclasspath="${tachyon_jar}:${sparkclasspath}"
+        sparkclasspath="${tachyon_jar}:${sparkclasspath}"
     else
-	sparkclasspath="${tachyon_jar}"
+        sparkclasspath="${tachyon_jar}"
     fi
 fi
 
@@ -555,12 +555,12 @@ if echo ${SPARK_VERSION} | grep -q -E "0\.9\.[0-9]"
 then 
     if [ "${sparkclasspath}X" != "X" ]
     then
-	echo "export SPARK_CLASSPATH=\"${sparkclasspath}\"" >> ${post_sparkenvsh}
+        echo "export SPARK_CLASSPATH=\"${sparkclasspath}\"" >> ${post_sparkenvsh}
     fi
 
     if [ "${SPARK_JOB_LIBRARY_PATH}X" != "X" ]
     then
-	echo "export SPARK_LIBRARY_PATH=\"${SPARK_JOB_LIBRARY_PATH}\"" >> ${post_sparkenvsh}
+        echo "export SPARK_LIBRARY_PATH=\"${SPARK_JOB_LIBRARY_PATH}\"" >> ${post_sparkenvsh}
     fi
 fi
 
@@ -586,7 +586,7 @@ then
     # If using Yarn, don't set this, Spark will use configuration of yarn.nodemanager.local-dirs 
     if [ "${SPARK_USE_YARN}" != "yes" ]
     then
-	echo "export SPARK_LOCAL_DIRS=\"${sparklocalscratchdirpath}\"" >> ${post_sparkenvsh}
+        echo "export SPARK_LOCAL_DIRS=\"${sparklocalscratchdirpath}\"" >> ${post_sparkenvsh}
     fi
 fi
 
@@ -614,9 +614,9 @@ if echo ${SPARK_VERSION} | grep -q -E "1\.[0-9]\.[0-9]"
 then
     if [ "${SPARK_USE_YARN}" == "yes" ]
     then
-	sparkmaster="yarn-client"
+        sparkmaster="yarn-client"
     else
-	sparkmaster="spark://${SPARK_MASTER_NODE}:${SPARK_MASTER_PORT}"
+        sparkmaster="spark://${SPARK_MASTER_NODE}:${SPARK_MASTER_PORT}"
     fi
     sparkmastersubst=`echo "${sparkmaster}" | sed "s/\\//\\\\\\\\\//g"`
 
@@ -628,30 +628,30 @@ then
 
     if [ "${SPARK_JOB_LIBRARY_PATH}X" != "X" ]
     then
-	sparklibrarypathsubst=`echo "${SPARK_JOB_LIBRARY_PATH}" | sed "s/\\//\\\\\\\\\//g"`
+        sparklibrarypathsubst=`echo "${SPARK_JOB_LIBRARY_PATH}" | sed "s/\\//\\\\\\\\\//g"`
         sparkdriverlibrarypathsubst=`echo "${SPARK_JOB_LIBRARY_PATH}" | sed "s/\\//\\\\\\\\\//g"`
     fi
 
     if [ "${TACHYON_SETUP}" == "yes" ]
     then
-	sparktachyonstoreurl="tachyon://${TACHYON_MASTER_NODE}:${TACHYON_MASTER_PORT}"
-	sparktachyonstoreurlsubst=`echo "${sparktachyonstoreurl}" | sed "s/\\//\\\\\\\\\//g"`
+        sparktachyonstoreurl="tachyon://${TACHYON_MASTER_NODE}:${TACHYON_MASTER_PORT}"
+        sparktachyonstoreurlsubst=`echo "${sparktachyonstoreurl}" | sed "s/\\//\\\\\\\\\//g"`
     fi
 
     cp ${pre_sparkdefaultsconf} ${post_sparkdefaultsconf}
 
     if [ "${pre_sparkdefaultsconf_tachyon}X" != "X" ]
     then
-	sed -i -e "/@TACHYON@/{r ${pre_sparkdefaultsconf_tachyon}" -e "d}" ${post_sparkdefaultsconf}
+        sed -i -e "/@TACHYON@/{r ${pre_sparkdefaultsconf_tachyon}" -e "d}" ${post_sparkdefaultsconf}
     else
-	sed -i -e "/@TACHYON@/,+1d" ${post_sparkdefaultsconf}
+        sed -i -e "/@TACHYON@/,+1d" ${post_sparkdefaultsconf}
     fi
 
     if [ "${pre_sparkdefaultsconf_yarn}X" != "X" ]
     then
-	sed -i -e "/@YARN@/{r ${pre_sparkdefaultsconf_yarn}" -e "d}" ${post_sparkdefaultsconf}
+        sed -i -e "/@YARN@/{r ${pre_sparkdefaultsconf_yarn}" -e "d}" ${post_sparkdefaultsconf}
     else
-	sed -i -e "/@YARN@/,+1d" ${post_sparkdefaultsconf}
+        sed -i -e "/@YARN@/,+1d" ${post_sparkdefaultsconf}
     fi
 
     # This is not for legitimate security as it can easily be
@@ -664,31 +664,31 @@ then
     sparklocalscratchdirpathsubst=`echo "${sparklocalscratchdirpath}" | sed "s/\\//\\\\\\\\\//g"`
 
     sed -i \
-	-e "s/SPARKMASTER/${sparkmastersubst}/g" \
-	-e "s/SPARKSHUFFLEFILEBUFFERKB/${sparkshufflebufferkb}/g" \
-	-e "s/SPARKSHUFFLEFILEBUFFER/${sparkshufflebuffer}/g" \
-	-e "s/SPARKSHUFFLECONSOLIDATEFILES/${sparkshuffleconsolidatefiles}/g" \
-	-e "s/SPARKDEFAULTPARALLELISM/${sparkdefaultparallelism}/g" \
-	-e "s/SPARKEXECUTORMEMORY/${sparkmem}/g" \
-	-e "s/SPARKUIPORT/${SPARK_APPLICATION_DASHBOARD_PORT}/g" \
-	-e "s/SPARKEXECUTOREXTRACLASSPATH/${sparkclasspathsubst}/g" \
-	-e "s/SPARKEXECUTOREXTRALIBRARYPATH/${sparklibrarypathsubst}/g" \
-	-e "s/SPARKDRIVEREXTRACLASSPATH/${sparkdriverclasspathsubst}/g" \
-	-e "s/SPARKDRIVEREXTRALIBRARYPATH/${sparkdriverlibrarypathsubst}/g" \
-	-e "s/SPARKAKKATHREADS/${akkathreads}/g" \
-	-e "s/SPARKSTORAGEMEMORYFRACTION/${sparkstoragememoryfraction}/g" \
-	-e "s/SPARKSHUFFLEMEMORYFRACTION/${sparkshufflememoryfraction}/g" \
-	-e "s/SPARKMEMORYFRACTION/${sparkmemoryfraction}/g" \
-	-e "s/SPARKMEMORYSTORAGEFRACTION/${sparkmemorystoragefraction}/g" \
-	-e "s/SPARKDEPLOYSPREADOUT/${sparkdeployspreadout}/g" \
-	-e "s/SPARKTACHYONSTOREURL/${sparktachyonstoreurlsubst}/g" \
-	-e "s/SPARKAUTHENTICATESECRET/${sparkauthenticatesecret}/g" \
-	-e "s/EXTRASPARKJAVAOPTS/${extrasparkjavaoptssubst}/g" \
-	-e "s/SPARKYARNEXECUTORCORES/${workercores}/g" \
-	-e "s/SPARKYARNEXECUTORINSTANCES/${SPARK_SLAVE_COUNT}/g" \
-	-e "s/SPARKYARNEXECUTOROVERHEAD/${sparkmemoverhead}/g" \
-	-e "s/SPARKLOCALDIR/${sparklocalscratchdirpathsubst}/g" \
-	${post_sparkdefaultsconf}
+        -e "s/SPARKMASTER/${sparkmastersubst}/g" \
+        -e "s/SPARKSHUFFLEFILEBUFFERKB/${sparkshufflebufferkb}/g" \
+        -e "s/SPARKSHUFFLEFILEBUFFER/${sparkshufflebuffer}/g" \
+        -e "s/SPARKSHUFFLECONSOLIDATEFILES/${sparkshuffleconsolidatefiles}/g" \
+        -e "s/SPARKDEFAULTPARALLELISM/${sparkdefaultparallelism}/g" \
+        -e "s/SPARKEXECUTORMEMORY/${sparkmem}/g" \
+        -e "s/SPARKUIPORT/${SPARK_APPLICATION_DASHBOARD_PORT}/g" \
+        -e "s/SPARKEXECUTOREXTRACLASSPATH/${sparkclasspathsubst}/g" \
+        -e "s/SPARKEXECUTOREXTRALIBRARYPATH/${sparklibrarypathsubst}/g" \
+        -e "s/SPARKDRIVEREXTRACLASSPATH/${sparkdriverclasspathsubst}/g" \
+        -e "s/SPARKDRIVEREXTRALIBRARYPATH/${sparkdriverlibrarypathsubst}/g" \
+        -e "s/SPARKAKKATHREADS/${akkathreads}/g" \
+        -e "s/SPARKSTORAGEMEMORYFRACTION/${sparkstoragememoryfraction}/g" \
+        -e "s/SPARKSHUFFLEMEMORYFRACTION/${sparkshufflememoryfraction}/g" \
+        -e "s/SPARKMEMORYFRACTION/${sparkmemoryfraction}/g" \
+        -e "s/SPARKMEMORYSTORAGEFRACTION/${sparkmemorystoragefraction}/g" \
+        -e "s/SPARKDEPLOYSPREADOUT/${sparkdeployspreadout}/g" \
+        -e "s/SPARKTACHYONSTOREURL/${sparktachyonstoreurlsubst}/g" \
+        -e "s/SPARKAUTHENTICATESECRET/${sparkauthenticatesecret}/g" \
+        -e "s/EXTRASPARKJAVAOPTS/${extrasparkjavaoptssubst}/g" \
+        -e "s/SPARKYARNEXECUTORCORES/${workercores}/g" \
+        -e "s/SPARKYARNEXECUTORINSTANCES/${SPARK_SLAVE_COUNT}/g" \
+        -e "s/SPARKYARNEXECUTOROVERHEAD/${sparkmemoverhead}/g" \
+        -e "s/SPARKLOCALDIR/${sparklocalscratchdirpathsubst}/g" \
+        ${post_sparkdefaultsconf}
     
     # Remove lingering "-bin-hadoop2.4" and similar text"
 
@@ -707,9 +707,9 @@ then
     vercomp_result=$?
     if [ "${vercomp_result}" == "1" ]
     then
-	sed -i -e "s/spark.shuffle.file.buffer.kb/# spark.shuffle.file.buffer.kb/" ${post_sparkdefaultsconf}
+        sed -i -e "s/spark.shuffle.file.buffer.kb/# spark.shuffle.file.buffer.kb/" ${post_sparkdefaultsconf}
     else
-	sed -i -e "s/spark.shuffle.file.buffer\s/# spark.shuffle.file.buffer/" ${post_sparkdefaultsconf}
+        sed -i -e "s/spark.shuffle.file.buffer\s/# spark.shuffle.file.buffer/" ${post_sparkdefaultsconf}
     fi
 
     # Handle special settings depending on version
@@ -718,11 +718,11 @@ then
     vercomp_result=$?
     if [ "${vercomp_result}" == "1" ]
     then
-	sed -i -e "s/spark.storage.memoryFraction/# spark.storage.memoryFraction/" ${post_sparkdefaultsconf}
-	sed -i -e "s/spark.shuffle.memoryFraction/# spark.shuffle.memoryFraction/" ${post_sparkdefaultsconf}
+        sed -i -e "s/spark.storage.memoryFraction/# spark.storage.memoryFraction/" ${post_sparkdefaultsconf}
+        sed -i -e "s/spark.shuffle.memoryFraction/# spark.shuffle.memoryFraction/" ${post_sparkdefaultsconf}
     else
-	sed -i -e "s/spark.memory.fraction/# spark.memory.fraction/" ${post_sparkdefaultsconf}
-	sed -i -e "s/spark.memory.storageFraction/# spark.memory.storageFraction/" ${post_sparkdefaultsconf}
+        sed -i -e "s/spark.memory.fraction/# spark.memory.fraction/" ${post_sparkdefaultsconf}
+        sed -i -e "s/spark.memory.storageFraction/# spark.memory.storageFraction/" ${post_sparkdefaultsconf}
     fi
     
     # spark authenticate doesn't work with yarn in Spark 1.2 -> 1.5.
@@ -737,9 +737,9 @@ then
     # Comment out a few lines we don't need if using Yarn
     if [ "${SPARK_USE_YARN}" == "yes" ] && [ "${vercomp_result}" != "1" ]
     then
-	sed -i \
-	    -e "s/spark.authenticate/# spark.authenticate/g" \
-	    ${post_sparkdefaultsconf}
+        sed -i \
+            -e "s/spark.authenticate/# spark.authenticate/g" \
+            ${post_sparkdefaultsconf}
     fi
 fi
 
diff --git a/magpie-setup-storm b/magpie-setup-storm
--- a/magpie-setup-storm
+++ b/magpie-setup-storm
@@ -53,8 +53,8 @@ if [ ! -d "${stormlocaldir}" ]
 then
     mkdir -p ${stormlocaldir}
     if [ $? -ne 0 ] ; then
-	echo "mkdir failed making ${stormlocaldir}"
-	exit 1
+        echo "mkdir failed making ${stormlocaldir}"
+        exit 1
     fi
 fi
 
@@ -69,7 +69,7 @@ else
 
     if [ "${stormslotcount}" == "0" ]
     then
-	stormslotcount="1"
+        stormslotcount="1"
     fi
 fi
 
diff --git a/magpie-setup-tachyon b/magpie-setup-tachyon
--- a/magpie-setup-tachyon
+++ b/magpie-setup-tachyon
@@ -57,11 +57,11 @@ do
     
     if [ ! -d "${tachyonstorefiletmp}" ]
     then
-	mkdir -p ${tachyonstorefiletmp}
-	if [ $? -ne 0 ] ; then
-	    echo "mkdir failed making ${tachyonstorefiletmp}"
-	    exit 1
-	fi
+        mkdir -p ${tachyonstorefiletmp}
+        if [ $? -ne 0 ] ; then
+            echo "mkdir failed making ${tachyonstorefiletmp}"
+            exit 1
+        fi
     fi
     
     tachyonstorepaths="${tachyonstorepaths}${tachyonstorepaths:+","}${tachyonstorepathstmp}"
@@ -107,11 +107,11 @@ then
     openfilescount=`expr ${openfilesslavecount} \* 4096`
     if [ "${openfilescount}" -lt "8192" ]
     then
-	openfilescount=8192
+        openfilescount=8192
     fi
     if [ "${openfilescount}" -gt "65536" ]
     then
-	openfilescount=65536
+        openfilescount=65536
     fi
     
     if [ "${openfileshardlimit}" != "unlimited" ]
@@ -135,11 +135,11 @@ then
     userprocessescount=`expr ${userprocessesslavecount} \* 2048`
     if [ "${userprocessescount}" -lt "4096" ]
     then
-	userprocessescount=4096
+        userprocessescount=4096
     fi
     if [ "${userprocessescount}" -gt "32768" ]
     then
-	userprocessescount=32768
+        userprocessescount=32768
     fi
     
     if [ "${userprocesseshardlimit}" != "unlimited" ]
diff --git a/magpie-setup-zookeeper b/magpie-setup-zookeeper
--- a/magpie-setup-zookeeper
+++ b/magpie-setup-zookeeper
@@ -58,44 +58,44 @@ then
         zookeeperdatadirpath="${ZOOKEEPER_DATA_DIR}/node-${zookeepernoderank}"
     fi
     zookeeperdatadirpathsubst=`echo "${zookeeperdatadirpath}" | sed "s/\\//\\\\\\\\\//g"`
-	
+        
     mkdir -p ${zookeeperdatadirpath}
     if [ $? -ne 0 ] ; then
-	echo "mkdir failed making ${zookeeperdatadirpath}"
-	exit 1
+        echo "mkdir failed making ${zookeeperdatadirpath}"
+        exit 1
     fi
     
     echo "${zookeepernoderank}" > ${zookeeperdatadirpath}/myid
     
     if [ "${ZOOKEEPER_TICKTIME}X" != "X" ]
     then
-	zookeeperticktime=${ZOOKEEPER_TICKTIME}
+        zookeeperticktime=${ZOOKEEPER_TICKTIME}
     else
-	zookeeperticktime=2000
+        zookeeperticktime=2000
     fi
     
     if [ "${ZOOKEEPER_INITLIMIT}X" != "X" ]
     then
-	zookeeperinitlimit=${ZOOKEEPER_INITLIMIT}
+        zookeeperinitlimit=${ZOOKEEPER_INITLIMIT}
     else
-	if [ "${ZOOKEEPER_DATA_DIR_TYPE}" == "local" ]
-	then
-	    zookeeperinitlimit=10
-	else
-	    zookeeperinitlimit=20
-	fi
+        if [ "${ZOOKEEPER_DATA_DIR_TYPE}" == "local" ]
+        then
+            zookeeperinitlimit=10
+        else
+            zookeeperinitlimit=20
+        fi
     fi
     
     if [ "${ZOOKEEPER_SYNCLIMIT}X" != "X" ]
     then
-	zookeepersynclimit=${ZOOKEEPER_SYNCLIMIT}
+        zookeepersynclimit=${ZOOKEEPER_SYNCLIMIT}
     else
-	if [ "${ZOOKEEPER_DATA_DIR_TYPE}" == "local" ]
-	then
-	    zookeepersynclimit=5
-	else
-	    zookeepersynclimit=10
-	fi
+        if [ "${ZOOKEEPER_DATA_DIR_TYPE}" == "local" ]
+        then
+            zookeepersynclimit=5
+        else
+            zookeepersynclimit=10
+        fi
     fi
 fi
 
