Fix Spark wordcount check, requries hadoop setup & hdfs

diff --git a/magpie-check-inputs b/magpie-check-inputs
--- a/magpie-check-inputs
+++ b/magpie-check-inputs
@@ -1040,18 +1040,34 @@ then
 
 	    if echo ${SPARK_SPARKWORDCOUNT_FILE} | grep -q -E "^hdfs:\/\/"
 	    then
-		if [ "${HADOOP_HOME}X" == "X" ]
+		if [ "${HADOOP_SETUP}" != "yes" ]
 		then
-		    echo "Cannot copy in file to SPARK_SPARKWORDCOUNT_FILE without HADOOP_HOME set"
+		    echo "Cannot copy in file to SPARK_SPARKWORDCOUNT_FILE without HADOOP_HOME setup"
+		    exit 1
+		fi
+
+		if [ "${HADOOP_FILESYSTEM_MODE}" != "hdfs" ] \
+		    && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsoverlustre" ] \
+		    && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsovernetworkfs" ]
+		then
+		    echo "Cannot copy in file to SPARK_SPARKWORDCOUNT_FILE, HADOOP_FILESYSTEM_MODE not set to an HDFS filesystem"
 		    exit 1
 		fi
 	    fi
 
 	    if echo ${SPARK_SPARKWORDCOUNT_COPY_IN_FILE} | grep -q -E "^hdfs:\/\/"
 	    then
-		if [ "${HADOOP_HOME}X" == "X" ]
+		if [ "${HADOOP_SETUP}" != "yes" ]
 		then
-		    echo "Cannot copy file from SPARK_SPARKWORDCOUNT_COPY_IN_FILE without HADOOP_HOME set"
+		    echo "Cannot copy file from SPARK_SPARKWORDCOUNT_COPY_IN_FILE without HADOOP setup"
+		    exit 1
+		fi
+
+		if [ "${HADOOP_FILESYSTEM_MODE}" != "hdfs" ] \
+		    && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsoverlustre" ] \
+		    && [ "${HADOOP_FILESYSTEM_MODE}" != "hdfsovernetworkfs" ]
+		then
+		    echo "Cannot copy file from SPARK_SPARKWORDCOUNT_COPY_IN_FILE, HADOOP_FILESYSTEM_MODE not set to an HDFS filesystem"
 		    exit 1
 		fi
 	    fi
