Add 'scriptnokill' option to magpie-run-job-wait-mode.
There are a few scripts we do not want user to be able to kill early.

diff --git a/magpie-run-job-wait-mode b/magpie-run-job-wait-mode
--- a/magpie-run-job-wait-mode
+++ b/magpie-run-job-wait-mode
@@ -39,7 +39,11 @@ then
     exit 1
 fi
 
-if [ "$1" != "interactive" ] && [ "$1" != "launch" ] && [ "$1" != "server" ] && [ "$1" != "script" ]
+if [ "$1" != "interactive" ] \
+    && [ "$1" != "launch" ] \
+    && [ "$1" != "server" ] \
+    && [ "$1" != "script" ] \
+    && [ "$1" != "scriptnokill" ]
 then
     echo "Internal error - magpie-job-wait-mode, first argument invalid = $1"
     exit 1
@@ -47,7 +51,7 @@ fi
 
 jobwaittype=$1
 
-if [ "${jobwaittype}" == "script" ]
+if [ "${jobwaittype}" == "script" ] || [ "${jobwaittype}" == "scriptnokill" ]
 then
     if [ "$2X" == "X" ]
     then
@@ -70,26 +74,30 @@ then
     ${MAGPIE_SCRIPTS_HOME}/magpie-run-sleep normal &
     childpid=$!
     typemessage="'${jobwaittype}' mode"
-else
+elif [ "${jobwaittype}" == "script" ] || [ "${jobwaittype}" == "scriptnokill" ]
+then
     ${scripttorun} &
     childpid=$!
     typemessage="job"
 fi
 
+if [ "${jobwaittype}" != "scriptnokill" ]
+then
 # Some systems have SIGUSR1 as USR1 so we hardcode the value of 10
 
-echo "*******************************************************"
-echo "* Run '${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} $(hostname) kill -s 10 ${mypid}' to exit ${typemessage} early."
-if [ "${jobwaittype}" == "script" ]
-then
-    echo "*"
-    echo "* Warning: killing early may not kill jobs submitted to an internally"
-    echo "* managed scheduler within Magpie.  The job will be canceled during teardown"
-    echo "* of daemons.  Extraneous error messages from your job may occur until then."
-fi
-echo "*******************************************************"
+    echo "*******************************************************"
+    echo "* Run '${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} $(hostname) kill -s 10 ${mypid}' to exit ${typemessage} early."
+    if [ "${jobwaittype}" == "script" ]
+    then
+	echo "*"
+	echo "* Warning: killing early may not kill jobs submitted to an internally"
+	echo "* managed scheduler within Magpie.  The job will be canceled during teardown"
+	echo "* of daemons.  Extraneous error messages from your job may occur until then."
+    fi
+    echo "*******************************************************"
 
-trap "echo \"Received interrupt from user, ${typemessage} ending early.\"; kill -s 9 ${childpid}" 10
+    trap "echo \"Received interrupt from user, ${typemessage} ending early.\"; kill -s 9 ${childpid}" 10
+fi    
 
 # Some systems have SIGUSR2 as USR2 so we hardcode the value of 12
 
