Create common function Magpie_check_service_up to handle common "has the service come up yet" checks in many projects

diff --git a/magpie-run-project-zookeeper b/magpie-run-project-zookeeper
--- a/magpie-run-project-zookeeper
+++ b/magpie-run-project-zookeeper
@@ -27,10 +27,34 @@
 source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-submission-type
 source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-dirs
 source ${MAGPIE_SCRIPTS_HOME}/magpie-exports-user
-source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-calculate-values
 source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-defaults
 source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-node-identification
 source ${MAGPIE_SCRIPTS_HOME}/magpie-lib-run
+
+# Return 0 if service up, 1 if not
+__Magpie_run_check_zookeeper_up () {
+    cd ${ZOOKEEPER_HOME}
+    
+    if ! type nc >/dev/null 2>&1
+    then
+        echo "Checking if zookeeper came up failed because netcat ('nc' command) was not found. Assuming success."
+        return 0
+    else 
+        local zookeepernodes=`cat ${ZOOKEEPER_CONF_DIR}/slaves`
+        for zookeepernode in ${zookeepernodes}
+        do
+            local zookeeperresponse=`echo ruok | nc ${zookeepernode} ${default_zookeeper_client_port}`
+            if [ "${zookeeperresponse}" != "imok" ]
+            then
+                return 1
+            fi
+        done
+        
+        return 0
+    fi  
+    
+    return 1
+}
 
 __Magpie_run_output_zookeeper_help () {
     echo "*   ${MAGPIE_REMOTE_CMD:-ssh}${MAGPIE_REMOTE_CMD_OPTS:+" "}${MAGPIE_REMOTE_CMD_OPTS} ${ZOOKEEPER_MASTER_NODE}"
@@ -129,54 +153,17 @@ Magpie_run_start_zookeeper () {
         
         if [ ${ZOOKEEPER_MODE} != "setuponly" ]
         then
-            # Will set magpie_waittimes_count
-            Magpie_calculate_waittimes_count
+            # Return 0 if service up, 1 if not
+            Magpie_check_service_up "Zookeeper" "__Magpie_run_check_zookeeper_up"
             
-            cd ${ZOOKEEPER_HOME}
-
-            local zookeepercameup=0
-            
-            local zookeepernodes=`cat ${ZOOKEEPER_CONF_DIR}/slaves`
-            if ! type nc >/dev/null 2>&1
+            if [ $? -eq 0 ]
             then
-                echo "Checking if zookeeper came up failed because netcat ('nc' command) was not found. Assuming success."
-                zookeepercameup=1
-            else 
-                for i in `seq 1 ${magpie_waittimes_count}`
-                do
-                    local zookeeperbadresponse=0
-                    
-                    for zookeepernode in ${zookeepernodes}
-                    do
-                        local zookeeperresponse=`echo ruok | nc ${zookeepernode} ${default_zookeeper_client_port}`
-                        if [ "${zookeeperresponse}" != "imok" ]
-                        then
-                            zookeeperbadresponse=1
-                            break
-                        fi
-                    done
-                    
-                    if [ "${zookeeperbadresponse}" == "0" ]
-                    then
-                        zookeepercameup=1
-                        break
-                    fi
-                    
-                    echo "Waiting 30 more seconds for Zookeeper daemons to come up"
-                    sleep 30
-                    magpie_run_total_sleep_wait=`expr ${magpie_run_total_sleep_wait} + 30`
-                done
-            fi  
-            
-            if [ "${zookeepercameup}" == "0" ]
-            then
-                echo "Atleast 1 Zookeeper daemon never came up, setup problem or maybe need to increase MAGPIE_STARTUP_TIME"
+                magpie_run_zookeeper_should_be_torndown=1
+                magpie_run_zookeeper_setup_successful=1
+            else
                 magpie_run_zookeeper_should_be_torndown=1
                 magpie_run_zookeeper_setup_successful=0
                 magpie_run_prior_startup_successful=false
-            else
-                magpie_run_zookeeper_should_be_torndown=1
-                magpie_run_zookeeper_setup_successful=1
             fi
         else
             magpie_run_zookeeper_should_be_torndown=1
