check that conf files exist in setup code

diff --git a/magpie-setup-hadoop b/magpie-setup-hadoop
--- a/magpie-setup-hadoop
+++ b/magpie-setup-hadoop
@@ -816,6 +816,25 @@ else
     exit 1
 fi
 
+if [ ! -f "${pre_coresitexml}" ] \
+    || [ ! -f "${pre_mapredsitexml}" ] \
+    || [ ! -f "${pre_hadoopenvsh}" ] \
+    || [ ! -f "${pre_hdfssitexml}" ] \
+    || [ ! -f "${pre_log4jproperties}" ] \
+    || ( [ "${pre_mapredenvsh}X" != "X" ] && [ ! -f "${pre_mapredenvsh}" ] ) \
+    || ( [ "${pre_yarnsitexml}X" != "X" ] && [ ! -f "${pre_yarnsitexml}" ] ) \
+    || ( [ "${pre_yarnenvsh}X" != "X" ] && [ ! -f "${pre_yarnenvsh}" ] ) \
+    || ( [ "${pre_mapredsitexml_uda}X" != "X" ] && [ ! -f "${pre_mapredsitexml_uda}" ] ) \
+    || ( [ "${pre_yarnsitexml_uda}X" != "X" ] && [ ! -f "${pre_yarnsitexml_uda}" ] ) \
+    || ( [ "${pre_coresitexml_intellustre}X" != "X" ] && [ ! -f "${pre_coresitexml_intellustre}" ] ) \
+    || ( [ "${pre_coresitexml_magpienetworkfs}X" != "X" ] && [ ! -f "${pre_coresitexml_magpienetworkfs}" ] ) \
+    || ( [ "${pre_coresitexml_tachyon}X" != "X" ] && [ ! -f "${pre_coresitexml_tachyon}" ] ) \
+    || ( [ "${pre_coresitexml_viewfsmount}X" != "X" ] && [ ! -f "${pre_coresitexml_viewfsmount}" ] )
+then
+    echo "Missing configuration files in ${hadoopconffiledir}"
+    exit 1
+fi
+
 post_coresitexml=${HADOOP_CONF_DIR}/core-site.xml
 post_mapredsitexml=${HADOOP_CONF_DIR}/mapred-site.xml
 post_hadoopenvsh=${HADOOP_CONF_DIR}/hadoop-env.sh
diff --git a/magpie-setup-hbase b/magpie-setup-hbase
--- a/magpie-setup-hbase
+++ b/magpie-setup-hbase
@@ -220,6 +220,14 @@ pre_hbasesitexml=${hbaseconffiledir}/hbase-site.xml
 pre_hbaseenvsh=${hbaseconffiledir}/hbase-env.sh
 pre_log4jproperties=${hbaseconffiledir}/hbase.log4j.properties
 
+if [ ! -f "${pre_hbasesitexml}" ] \
+    || [ ! -f "${pre_hbaseenvsh}" ] \
+    || [ ! -f "${pre_log4jproperties}" ]
+then
+    echo "Missing configuration files in ${hbaseconffiledir}"
+    exit 1
+fi
+
 post_hbasesitexml=${HBASE_CONF_DIR}/hbase-site.xml
 post_hbaseenvsh=${HBASE_CONF_DIR}/hbase-env.sh
 post_log4jproperties=${HBASE_CONF_DIR}/log4j.properties
diff --git a/magpie-setup-pig b/magpie-setup-pig
--- a/magpie-setup-pig
+++ b/magpie-setup-pig
@@ -53,6 +53,13 @@ fi
 pre_pigproperties=${pigconffiledir}/pig.properties
 pre_log4jproperties=${pigconffiledir}/pig.log4j.properties
 
+if [ ! -f "${pre_pigproperties}" ] \
+    || [ ! -f "${pre_log4jproperties}" ]
+then
+    echo "Missing configuration files in ${pigconffiledir}"
+    exit 1
+fi
+
 post_pigproperties=${PIG_CONF_DIR}/pig.properties
 post_log4jproperties=${PIG_CONF_DIR}/log4j.properties
 
diff --git a/magpie-setup-spark b/magpie-setup-spark
--- a/magpie-setup-spark
+++ b/magpie-setup-spark
@@ -395,6 +395,15 @@ then
     pre_sparkdefaultsconf_tachyon=${sparkconffiledir}/spark-defaults.conf-tachyon
 fi
 
+if [ ! -f "${pre_sparkenvsh}" ] \
+    || [ ! -f "${pre_sparkdefaultsconf}" ] \
+    || [ ! -f "${pre_log4jproperties}" ] \
+    || ( [ "${pre_sparkdefaultsconf_tachyon}X" != "X" ] && [ ! -f "${pre_sparkdefaultsconf_tachyon}" ] )
+then
+    echo "Missing configuration files in ${sparkconffiledir}"
+    exit 1
+fi
+
 post_sparkenvsh=${SPARK_CONF_DIR}/spark-env.sh
 post_sparkdefaultsconf=${SPARK_CONF_DIR}/spark-defaults.conf
 post_log4jproperties=${SPARK_CONF_DIR}/log4j.properties
diff --git a/magpie-setup-storm b/magpie-setup-storm
--- a/magpie-setup-storm
+++ b/magpie-setup-storm
@@ -129,6 +129,14 @@ pre_stormyaml=${stormconffiledir}/storm.yaml
 pre_stormenvini=${stormconffiledir}/storm_env.ini
 pre_stormenvsh=${stormconffiledir}/magpie-launch-storm-env.sh
 
+if [ ! -f "${pre_stormyaml}" ] \
+    || [ ! -f "${pre_stormenvini}" ] \
+    || [ ! -f "${pre_stormenvsh}" ]
+then
+    echo "Missing configuration files in ${stormconffiledir}"
+    exit 1
+fi
+
 post_stormyaml=${STORM_CONF_DIR}/storm.yaml
 post_stormenvini=${STORM_CONF_DIR}/storm_env.ini
 post_stormenvsh=${STORM_CONF_DIR}/magpie-launch-storm-env.sh
diff --git a/magpie-setup-tachyon b/magpie-setup-tachyon
--- a/magpie-setup-tachyon
+++ b/magpie-setup-tachyon
@@ -166,6 +166,13 @@ fi
 pre_tachyonenvsh=${tachyonconffiledir}/tachyon-env.sh
 pre_log4jproperties=${tachyonconffiledir}/tachyon.log4j.properties
 
+if [ ! -f "${pre_tachyonenvsh}" ] \
+    || [ ! -f "${pre_log4jproperties}" ]
+then
+    echo "Missing configuration files in ${tachyonconffiledir}"
+    exit 1
+fi
+
 post_tachyonenvsh=${TACHYON_CONF_DIR}/tachyon-env.sh
 post_log4jproperties=${TACHYON_CONF_DIR}/log4j.properties
 
diff --git a/magpie-setup-zookeeper b/magpie-setup-zookeeper
--- a/magpie-setup-zookeeper
+++ b/magpie-setup-zookeeper
@@ -132,6 +132,14 @@ pre_zookeepercfg=${zookeeperconffiledir}/zoo.cfg
 pre_zookeeperenvsh=${zookeeperconffiledir}/zookeeper-env.sh
 pre_log4jproperties=${zookeeperconffiledir}/zookeeper.log4j.properties
 
+if [ ! -f "${pre_zookeepercfg}" ] \
+    || [ ! -f "${pre_zookeeperenvsh}" ] \
+    || [ ! -f "${pre_log4jproperties}" ]
+then
+    echo "Missing configuration files in ${zookeeperconffiledir}"
+    exit 1
+fi
+
 post_zookeepercfg=${ZOOKEEPER_CONF_DIR}/zoo.cfg
 post_zookeeperenvsh=${ZOOKEEPER_CONF_DIR}/zookeeper-env.sh
 post_log4jproperties=${ZOOKEEPER_CONF_DIR}/log4j.properties
